function config = adc128Config()
%ADC128CONFIG Bandwidth settings for 12-bit unipolar ADC128 ILA captures.
config = struct('deviceId', 'ADC128', 'analysisId', 'bandwidth', ...
    'version', '0.2.0', 'releaseReady', false, 'formalEnabled', false, ...
    'adcBits', 12, 'adcFullScalePeakCode', 2048, ...
    'adcCodeFormat', 'unsigned', ...
    'adcDataColumn', 5, ...
    'validDataColumn', 4, ...
    'filterValidStrobe', true, ...
    'ilaClockHz', 50e6, ...
    'sampleRate', NaN, ...
    'fitCycles', 20, 'minimumFitSamples', 1024, ...
    'minimumFitR2', 0.99, 'referencePointCount', 3, ...
    'frequencyMismatchTolerance', 0.02, 'rejectFrequencyMismatch', true, ...
    'bandwidthFrequencySource', 'file', 'clippingMarginCode', 1, ...
    'clippingMarginLowCode', -1, ...
    'saveFigures', true, 'showFigures', false);
% CSV layout (Vivado ILA export of module_adc128_top):
%   col1 Sample in Buffer, col2 Sample in Window, col3 TRIGGER,
%   col4 data_128_vld (strobe), col5 data_128[11:0] (12-bit unsigned code).
% The ILA records at ilaClockHz = 50 MHz, but data_128 only updates on the
% col4 strobe (every 500 ILA cycles on the 20260917 captures, i.e. 100 kS/s).
% Rows without the strobe are held codes and are dropped by readAdcCsv via
% validDataColumn. sampleRate stays NaN here and is filled per run from the
% measured strobe spacing (ilaClockHz / strobePeriod); a finite sampleRate
% passed through runOptions overrides the derivation for explicit runs.
% clippingMarginLowCode = -1 relaxes only the bottom rail: the 2.5 Vpp /
% 1.25 V offset places the trough right at raw code 0, and touching 0 is
% accepted by decision so the low-frequency files still join the fit. The
% top rail keeps the legacy 1-code margin via clippingMarginCode.
end
