function config = adc128Config()
%ADC128CONFIG Bandwidth settings for 12-bit unipolar ADC128 captures.
config = struct('deviceId', 'ADC128', 'analysisId', 'bandwidth', ...
    'version', '0.1.0', 'releaseReady', false, 'formalEnabled', false, ...
    'adcBits', 12, 'adcFullScalePeakCode', 2048, ...
    'adcCodeFormat', 'unsigned', 'adcDataColumn', 4, ...
    'sampleRate', NaN, 'fitCycles', 20, 'minimumFitSamples', 1024, ...
    'minimumFitR2', 0.99, 'referencePointCount', 3, ...
    'frequencyMismatchTolerance', 0.02, 'rejectFrequencyMismatch', true, ...
    'bandwidthFrequencySource', 'file', 'clippingMarginCode', 1, ...
    'saveFigures', true, 'showFigures', false);
% No clock rate is inferred from the ADC name or the AD2208 reference entry.
end
