function [fitresult, gof, fitInfo] = sine_fit(data, fin, fs)
%  Create a fit.
%
%  Data for '4 parameters sine fitting' fit:
%      Y Output: data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Oct-2015 16:08:02


%%
aStart = (max(data) - min(data))/2;
aLower = aStart - 100;
aUpper = aStart + 100;
% aUpper = min(aStart+100, 2048);

bStart = fin/fs;
bLower = bStart*0.99;
bUpper = bStart*1.01;
% bLower = bStart * 0.9;
% bUpper = bStart * 1.1;

cStart = 0;
cLower = -pi;
cUpper = pi;

dStart = mean(data);
dLower = dStart - 10;
dUpper = dStart + 10;

data = data(1:round(fs/fin*10)); % only fit 8 periods data
[xData, yData] = prepareCurveData( [], data );

% Set up fittype and options.
ft = fittype( 'a*sin(2*pi*b*x+c)+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';


opts.StartPoint = [aStart, bStart, cStart, dStart];
opts.Lower = [aLower, bLower, cLower, dLower];
opts.Upper = [aUpper, bUpper, cUpper, dUpper];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Fitted sine-wave code levels.
fitParameter = coeffvalues(fitresult);
fitAmplitudeCode = abs(fitParameter(1));
fitOffsetCode = fitParameter(4);
fitPeakCode = fitOffsetCode + fitAmplitudeCode;
fitValleyCode = fitOffsetCode - fitAmplitudeCode;
% For a fitted sine wave, all ideal cycle peaks have the same value.
% Therefore, their average equals the fitted positive peak.
fitPeakAverageCode = fitPeakCode;
fitCenterCode = (fitPeakCode + fitValleyCode)/2;
fitCodePp = fitPeakCode - fitValleyCode;

fitInfo = struct( ...
    'amplitudeCode', fitAmplitudeCode, ...
    'offsetCode', fitOffsetCode, ...
    'peakCode', fitPeakCode, ...
    'valleyCode', fitValleyCode, ...
    'peakAverageCode', fitPeakAverageCode, ...
    'centerCode', fitCenterCode, ...
    'codePp', fitCodePp);

% Plot fit with data.
% %{
fitInfo.figureHandle = figure('Name', 'Sine Fitting', 'Visible', 'on');
h = plot(fitresult, xData, yData);
legend( h, 'Data Points', 'Sine Fitting Curve', 'Location', 'NorthEast' );
% Label axes
ylabel('ADC Code')
hold on
grid on
yline(fitPeakCode, '--r', 'Fitted peak');
yline(fitValleyCode, '--m', 'Fitted valley');
text(0.02, 0.95, sprintf(['Fitted peak       = %.3f code\n' ...
    'Fitted valley     = %.3f code\n' ...
    'Peak average      = %.3f code\n' ...
    'Center code       = %.3f code\n' ...
    'Amplitude         = %.3f code\n' ...
    'Offset            = %.3f code'], ...
    fitPeakCode, fitValleyCode, fitPeakAverageCode, fitCenterCode, ...
    fitAmplitudeCode, fitOffsetCode), ...
    'Units', 'normalized', 'VerticalAlignment', 'top', ...
    'FontSize', 12, 'FontWeight', 'bold', ...
    'BackgroundColor', 'w', 'EdgeColor', [0.3 0.3 0.3]);
text(0.02, 0.55, sprintf('Code_{pp} = %.3f code', fitCodePp), ...
    'Units', 'normalized', 'FontSize', 14, 'FontWeight', 'bold', ...
    'Color', 'r', 'BackgroundColor', 'w', 'EdgeColor', 'r');
end % grid on
% %}
