function spec = deviceReleaseRegistry(deviceName)
%DEVICERELEASEREGISTRY Return release metadata for a device directory.

deviceName = upper(strtrim(char(deviceName)));
switch deviceName
    case {'AD9245', '9245_HY'}
        spec = struct('deviceId', 'AD9245', 'folderName', '9245_hy', ...
            'version', '1.0.0', 'releaseReady', true, ...
            'allowedProducts', {{'MATLAB'}}, ...
            'entryFiles', {{'adc_sfdr_analysis.m', ...
            'adc_bandwidth_analysis.m', 'adc_isolation_analysis.m', ...
            'adc_power_scale_analysis.m', 'adc_inl_dnl_analysis.m'}});
    case {'AD2208', '2208_HY'}
        spec = struct('deviceId', 'AD2208', 'folderName', '2208_hy', ...
            'version', '1.3.0', 'releaseReady', true, ...
            'allowedProducts', {{'MATLAB'}}, ...
            'entryFiles', {{'adc_sfdr_analysis.m', ...
            'adc_bandwidth_analysis.m', 'adc_isolation_analysis.m', ...
            'adc_power_scale_analysis.m', 'adc_inl_dnl_analysis.m'}});
    case {'AD677', '677_HY'}
        spec = struct('deviceId', 'AD677', 'folderName', '677_hy', ...
            'version', '0.1.0', 'releaseReady', true, ...
            'allowedProducts', {{'MATLAB'}}, ...
            'entryFiles', {{'adc_bandwidth_analysis.m', ...
            'adc_power_scale_analysis.m', 'run_ad677_batch.m', ...
            'audit_ad677_results.m'}});
    case {'DA766', 'AD766', '766_HY'}
        spec = pendingSpec('DA766', '766_hy', ...
            {'dac_scale_analysis.m', 'dac_noise_analysis.m', ...
            'dac_isolation_analysis.m'});
    case {'DA9726', 'AD9726', '9726_HY'}
        spec = pendingSpec('DA9726', '9726_hy', ...
            {'dac_scale_analysis.m', 'dac_noise_analysis.m', ...
            'dac_isolation_analysis.m'});
    otherwise
        error('converter:build:UnknownDevice', '未知器件：%s。', deviceName);
end
end

function spec = pendingSpec(deviceId, folderName, entryFiles)
if nargin < 3, entryFiles = {}; end
spec = struct('deviceId', deviceId, 'folderName', folderName, ...
    'version', '0.1.0', 'releaseReady', true, ...
    'allowedProducts', {{'MATLAB', 'Signal Processing Toolbox'}}, ...
    'entryFiles', {entryFiles});
end
