function estimate = estimateCriticalInput(results, calibrationCoefficient, ...
        config, referenceImpedanceOhm)
%ESTIMATECRITICALINPUT Estimate the input where either ADC rail reaches a target.
%   ESTIMATE = ESTIMATECRITICALINPUT(RESULTS, COEFFICIENT, CONFIG, R)
%   fits the positive and negative fitted sine peaks versus input Vpp using
%   only RESULTS.CalibrationIncluded points. The first rail predicted to
%   reach CONFIG.criticalInputThresholdFraction of the signed peak code
%   defines the critical input estimate.

estimate = unavailableEstimate('critical input threshold is not configured');
if ~isfield(config, 'criticalInputThresholdFraction') || ...
        isempty(config.criticalInputThresholdFraction)
    return;
end

thresholdFraction = double(config.criticalInputThresholdFraction);
if ~isscalar(thresholdFraction) || ~isfinite(thresholdFraction) || ...
        thresholdFraction <= 0 || thresholdFraction >= 1
    error('converter:adc:InvalidCriticalInputThreshold', ...
        'criticalInputThresholdFraction 必须是 0 到 1 之间的有限标量。');
end

requiredVariables = {'InputVoltageVpp', 'PeakCode', 'ValleyCode', ...
    'CalibrationIncluded', 'ClippingFlag'};
if ~all(ismember(requiredVariables, results.Properties.VariableNames))
    error('converter:adc:InvalidCriticalInputMeasurements', ...
        '临界输入拟合缺少所需的功率刻度测量字段。');
end
if numel(calibrationCoefficient) ~= 2 || ...
        any(~isfinite(calibrationCoefficient)) || calibrationCoefficient(1) <= 0
    error('converter:adc:InvalidCriticalInputCalibration', ...
        'CodePp-to-Vpp 刻度系数必须是正斜率的一阶有限系数。');
end

inputVpp = double(results.InputVoltageVpp(:));
peakCode = double(results.PeakCode(:));
negativePeakCode = -double(results.ValleyCode(:));
included = logical(results.CalibrationIncluded(:));
fitMask = included & isfinite(inputVpp) & isfinite(peakCode) & ...
    isfinite(negativePeakCode);
if nnz(fitMask) < 2 || numel(unique(inputVpp(fitMask))) < 2
    estimate = unavailableEstimate('fewer than two distinct calibration inputs');
    estimate.thresholdFraction = thresholdFraction;
    return;
end

positiveRailFit = polyfit(inputVpp(fitMask), peakCode(fitMask), 1);
negativeRailFit = polyfit(inputVpp(fitMask), negativePeakCode(fitMask), 1);
positiveRailFitR2 = calculateFitR2(inputVpp(fitMask), peakCode(fitMask), ...
    positiveRailFit);
negativeRailFitR2 = calculateFitR2(inputVpp(fitMask), ...
    negativePeakCode(fitMask), negativeRailFit);

adcFullScalePeakCode = 2^(config.adcBits - 1);
thresholdPeakCode = thresholdFraction * adcFullScalePeakCode;
positiveCriticalVpp = solveRailCrossing(positiveRailFit, thresholdPeakCode);
negativeCriticalVpp = solveRailCrossing(negativeRailFit, thresholdPeakCode);
[criticalInputVpp, limitingRail] = selectLimitingRail( ...
    positiveCriticalVpp, negativeCriticalVpp);
lastUnclippedInputVpp = max(inputVpp(fitMask));

if ~isfinite(criticalInputVpp) || criticalInputVpp <= lastUnclippedInputVpp
    estimate = unavailableEstimate( ...
        'rail crossing is not above the calibrated input range');
    estimate.thresholdFraction = thresholdFraction;
    estimate.thresholdPeakCode = thresholdPeakCode;
    estimate.positiveRailFitR2 = positiveRailFitR2;
    estimate.negativeRailFitR2 = negativeRailFitR2;
    estimate.positiveRailCriticalVpp = positiveCriticalVpp;
    estimate.negativeRailCriticalVpp = negativeCriticalVpp;
    estimate.lastUnclippedInputVpp = lastUnclippedInputVpp;
    return;
end

clippedInputVpp = inputVpp(logical(results.ClippingFlag(:)) & ...
    isfinite(inputVpp) & inputVpp > lastUnclippedInputVpp);
if isempty(clippedInputVpp)
    firstClippedInputVpp = NaN;
else
    firstClippedInputVpp = min(clippedInputVpp);
end
isBracketed = isfinite(firstClippedInputVpp) && ...
    criticalInputVpp <= firstClippedInputVpp;
if isBracketed
    estimateStatus = "bracketed_estimate";
else
    estimateStatus = "unbracketed_extrapolation";
end

criticalCodePp = (criticalInputVpp - calibrationCoefficient(2)) / ...
    calibrationCoefficient(1);
criticalInputDbm = convertVppToDbm(criticalInputVpp, ...
    referenceImpedanceOhm);
lastUnclippedInputDbm = convertVppToDbm(lastUnclippedInputVpp, ...
    referenceImpedanceOhm);
firstClippedInputDbm = convertVppToDbm(firstClippedInputVpp, ...
    referenceImpedanceOhm);

estimate = struct( ...
    'available', true, ...
    'status', estimateStatus, ...
    'reason', "", ...
    'method', "linear rail fits using CalibrationIncluded points", ...
    'thresholdFraction', thresholdFraction, ...
    'thresholdPeakCode', thresholdPeakCode, ...
    'criticalCodePp', criticalCodePp, ...
    'criticalInputVpp', criticalInputVpp, ...
    'criticalInputDbm', criticalInputDbm, ...
    'limitingRail', limitingRail, ...
    'positiveRailCriticalVpp', positiveCriticalVpp, ...
    'negativeRailCriticalVpp', negativeCriticalVpp, ...
    'positiveRailFitR2', positiveRailFitR2, ...
    'negativeRailFitR2', negativeRailFitR2, ...
    'lastUnclippedInputVpp', lastUnclippedInputVpp, ...
    'firstClippedInputVpp', firstClippedInputVpp, ...
    'lastUnclippedInputDbm', lastUnclippedInputDbm, ...
    'firstClippedInputDbm', firstClippedInputDbm, ...
    'extrapolationRatio', criticalInputVpp / lastUnclippedInputVpp, ...
    'bracketed', isBracketed);
end

function fitR2 = calculateFitR2(inputValue, outputValue, coefficient)
predictedValue = polyval(coefficient, inputValue);
residual = outputValue - predictedValue;
fitR2 = 1 - sum(residual.^2) / ...
    max(sum((outputValue - mean(outputValue)).^2), eps);
end

function crossingVpp = solveRailCrossing(coefficient, thresholdPeakCode)
if coefficient(1) <= 0 || any(~isfinite(coefficient))
    crossingVpp = NaN;
else
    crossingVpp = (thresholdPeakCode - coefficient(2)) / coefficient(1);
    if ~isfinite(crossingVpp) || crossingVpp <= 0
        crossingVpp = NaN;
    end
end
end

function [criticalVpp, limitingRail] = selectLimitingRail(positiveVpp, negativeVpp)
if isfinite(positiveVpp) && (~isfinite(negativeVpp) || positiveVpp <= negativeVpp)
    criticalVpp = positiveVpp;
    limitingRail = "positive";
elseif isfinite(negativeVpp)
    criticalVpp = negativeVpp;
    limitingRail = "negative";
else
    criticalVpp = NaN;
    limitingRail = "unknown";
end
end

function inputDbm = convertVppToDbm(inputVpp, referenceImpedanceOhm)
if isfinite(inputVpp) && isscalar(referenceImpedanceOhm) && ...
        isfinite(referenceImpedanceOhm) && referenceImpedanceOhm > 0
    inputDbm = converter.adc.vppToDbm(inputVpp, referenceImpedanceOhm);
else
    inputDbm = NaN;
end
end

function estimate = unavailableEstimate(reason)
estimate = struct( ...
    'available', false, ...
    'status', "unavailable", ...
    'reason', string(reason), ...
    'method', "linear rail fits using CalibrationIncluded points", ...
    'thresholdFraction', NaN, ...
    'thresholdPeakCode', NaN, ...
    'criticalCodePp', NaN, ...
    'criticalInputVpp', NaN, ...
    'criticalInputDbm', NaN, ...
    'limitingRail', "unknown", ...
    'positiveRailCriticalVpp', NaN, ...
    'negativeRailCriticalVpp', NaN, ...
    'positiveRailFitR2', NaN, ...
    'negativeRailFitR2', NaN, ...
    'lastUnclippedInputVpp', NaN, ...
    'firstClippedInputVpp', NaN, ...
    'lastUnclippedInputDbm', NaN, ...
    'firstClippedInputDbm', NaN, ...
    'extrapolationRatio', NaN, ...
    'bracketed', false);
end
