function results = runInlDnl(config, dataFolder, selectedFileNames, outputFolder)
%RUNINLDNL Run the complete traceable sine-code-density workflow.

[fileNames, dataFolder] = converter.io.selectCsvFiles( ...
    dataFolder, selectedFileNames, '选择 ADC INL/DNL CSV 文件');
if isempty(fileNames)
    fprintf('未选择文件，INL/DNL 分析已取消。\n');
    results = table;
    return;
end
fileNames = sort(fileNames);
runContext = converter.runtime.createRun( ...
    config, dataFolder, fileNames, outputFolder);
try
    adcCodeList = cell(numel(fileNames), 1);
    for fileIndex = 1:numel(fileNames)
        filePath = converter.io.resolveInputPath(dataFolder, fileNames{fileIndex});
        adcCodeList{fileIndex} = converter.io.readAdcCsv(filePath, config);
        fprintf('INL/DNL 读取：%d/%d  %s\n', ...
            fileIndex, numel(fileNames), fileNames{fileIndex});
    end
    firstPath = converter.io.resolveInputPath(dataFolder, fileNames{1});
    channelName = converter.io.extractChannel(firstPath, config);
    if isempty(channelName)
        channelName = 'Unknown';
    end
    [results, details] = converter.adc.calculateInlDnl( ...
        adcCodeList, fileNames, channelName, config);
    [modifiedAt, modifiedElapsedSeconds] = getFileTimes( ...
        dataFolder, fileNames);
    details.captureTable.ModifiedAt = modifiedAt;
    details.captureTable.ModifiedElapsedSeconds = modifiedElapsedSeconds;
    converter.report.writeTable(results, ...
        fullfile(runContext.folder, 'ADC_inl_dnl_summary.csv'));
    converter.report.writeTable(details.curveTable, ...
        fullfile(runContext.folder, 'ADC_inl_dnl_curve.csv'));
    converter.report.writeTable(details.captureTable, ...
        fullfile(runContext.folder, 'ADC_inl_dnl_capture_metrics.csv'));
    analysisParameters = createParameterTable(config);
    converter.report.writeTable(analysisParameters, ...
        fullfile(runContext.folder, 'ADC_inl_dnl_analysis_parameters.csv'));
    save(fullfile(runContext.folder, 'ADC_inl_dnl_result.mat'), ...
        'results', 'details', 'analysisParameters');
    converter.report.plotInlDnl(details, runContext.folder, config);
    disp(results);
    fprintf('INL/DNL 结果已保存至：%s\n', runContext.folder);
    converter.runtime.finishRun(runContext, true, 'INL/DNL analysis completed.');
catch analysisError
    converter.runtime.finishRun(runContext, false, analysisError.message);
    rethrow(analysisError);
end
end

function parameterTable = createParameterTable(config)
%CREATEPARAMETERTABLE Persist the configuration used for this INL/DNL run.
parameterName = {'sample_rate_hz'; 'adc_bits'; 'adc_code_format'; ...
    'margin_code'; 'minimum_fit_r2'; 'frequency_refinement_cycles'; ...
    'frequency_refinement_minimum_samples'; ...
    'minimum_valid_capture_fraction'; 'glitch_sigma_multiplier'; ...
    'glitch_minimum_threshold_code'; 'maximum_glitch_fraction'; ...
    'clipping_margin_code'; 'records_are_sample_contiguous'; ...
    'fit_frequency_source'; 'code_density_method'};
parameterValue = {num2str(config.sampleRate, 15); num2str(config.adcBits); ...
    config.adcCodeFormat; num2str(config.marginCode, 15); ...
    num2str(config.minimumFitR2, 15); ...
    num2str(config.frequencyRefinementCycles, 15); ...
    num2str(config.frequencyRefinementMinimumSamples, 15); ...
    num2str(config.minimumValidCaptureFraction, 15); ...
    num2str(config.glitchSigmaMultiplier, 15); ...
    num2str(config.glitchMinimumThresholdCode, 15); ...
    num2str(config.maximumGlitchFraction, 15); ...
    num2str(config.clippingMarginCode, 15); ...
    char(string(logical(config.recordsAreSampleContiguous))); ...
    'FFT estimate refined by minimum sine-fit residual'; ...
    ['independent-record sine fits; sample-weighted mixture of ' ...
    'record-specific sine-code probabilities']};
parameterTable = table(parameterName, parameterValue, ...
    'VariableNames', {'Parameter', 'Value'});
end

function [modifiedAt, elapsedSeconds] = getFileTimes(dataFolder, fileNames)
fileCount = numel(fileNames);
modifiedAt = strings(fileCount, 1);
modifiedDatenum = NaN(fileCount, 1);
for fileIndex = 1:fileCount
    fileInfo = dir(converter.io.resolveInputPath(dataFolder, fileNames{fileIndex}));
    if isempty(fileInfo)
        continue;
    end
    modifiedDatenum(fileIndex) = fileInfo(1).datenum;
    modifiedAt(fileIndex) = string(datetime(fileInfo(1).datenum, ...
        'ConvertFrom', 'datenum', 'Format', 'yyyy-MM-dd HH:mm:ss'));
end
elapsedSeconds = NaN(fileCount, 1);
validTime = isfinite(modifiedDatenum);
if any(validTime)
    firstModifiedDatenum = modifiedDatenum(find(validTime, 1));
    elapsedSeconds(validTime) = ...
        (modifiedDatenum(validTime) - firstModifiedDatenum) * 86400;
end
end

