function results = runPowerScale(config, dataFolder, selectedFileNames, outputFolder, runOptions)
%RUNPOWERSCALE Run the traceable CodePp-to-Vpp calibration workflow.

if nargin < 5 || isempty(runOptions)
    runOptions = struct();
end
[fileNames, dataFolder] = converter.io.selectCsvFiles( ...
    dataFolder, selectedFileNames, '选择输入功率标定 CSV 文件');
if isempty(fileNames)
    fprintf('未选择文件，CodePp-to-Vpp 标定已取消。\n');
    results = table;
    return;
end

referenceImpedanceOhm = getReferenceImpedance(config);
if isfield(runOptions, 'powerSetpoints') && ...
        ~isempty(runOptions.powerSetpoints)
    [inputPowerDbm, setpointInfo] = resolveExplicitSetpoints( ...
        fileNames, runOptions.powerSetpoints, referenceImpedanceOhm);
else
    inputPowerDbm = cellfun(@converter.io.parsePowerDbm, fileNames);
    parseValid = isfinite(inputPowerDbm);
    if any(~parseValid)
        fprintf('以下文件名无法解析 dBm，已忽略：\n');
        fprintf('  %s\n', fileNames{~parseValid});
        fileNames = fileNames(parseValid);
        inputPowerDbm = inputPowerDbm(parseValid);
    end
    setpointInfo = defaultSetpointInfo(numel(fileNames), inputPowerDbm, ...
        referenceImpedanceOhm);
end
if isempty(fileNames)
    error('converter:adc:NoPowerInput', '没有可解析输入功率的 CSV 文件。');
end
if any(~isfinite(setpointInfo.inputVoltageVpp)) || ...
        any(setpointInfo.inputVoltageVpp <= 0)
    error('converter:adc:InvalidVppSetpoint', ...
        '输入功率标定必须提供或换算出正的 Vpp。');
end

runContext = converter.runtime.createRun( ...
    config, dataFolder, fileNames, outputFolder);
try
    fileCount = numel(fileNames);
    adcCodeList = cell(fileCount, 1);
    channelNames = strings(fileCount, 1);
    for fileIndex = 1:fileCount
        filePath = converter.io.resolveInputPath(dataFolder, fileNames{fileIndex});
        channelNames(fileIndex) = converter.io.detectChannel( ...
            filePath, fileNames{fileIndex}, dataFolder, config);
        adcCodeList{fileIndex} = converter.io.readAdcCsv(filePath, config);
    end
    [results, details] = converter.adc.calculatePowerScale( ...
        adcCodeList, fileNames, inputPowerDbm, channelNames, config, ...
        setpointInfo);
    setpointTable = buildSetpointManifest(fileNames, inputPowerDbm, ...
        setpointInfo);
    converter.report.writeTable(setpointTable, fullfile( ...
        runContext.folder, 'input_power_setpoint_manifest.csv'));
    converter.report.writeTable(results, fullfile( ...
        runContext.folder, 'ADC_vpp_codepp_summary.csv'));
    converter.report.writeTable(results, fullfile( ...
        runContext.folder, 'ADC_vpp_codepp_measurements.csv'));
    converter.report.writeTable(createParameterTable(config, details), ...
        fullfile(runContext.folder, 'analysis_parameters.csv'));
    converter.report.writeTable(createCalibrationTable(config, details), ...
        fullfile(runContext.folder, 'ADC_vpp_codepp_calibration.csv'));
    converter.report.writeTable(createCriticalInputTable(details), ...
        fullfile(runContext.folder, 'ADC_critical_input_estimate.csv'));
    save(fullfile(runContext.folder, 'ADC_vpp_codepp_result.mat'), ...
        'results', 'details', 'setpointTable');
    converter.report.plotPowerScale(results, details, runContext.folder, config);
    disp(results);
    fprintf('\n通道：%s\n', char(details.channelName));
    fprintf('CodePp-Vpp 标定斜率：%.12g Vpp/CodePp\n', ...
        details.coefficient(1));
    fprintf('CodePp-Vpp 标定截距：%.12g Vpp\n', details.coefficient(2));
    fprintf('标定 R^2：%.8f\n', details.calibrationR2);
    fprintf('CodePp 到 Vpp 刻度公式：%s\n', ...
        details.forwardFormulaCodePpToVpp);
    printCriticalInput(details.criticalInput);
    fprintf('CodePp-Vpp 标定结果已保存至：%s\n', runContext.folder);
    converter.runtime.finishRun(runContext, true, ...
        'CodePp-to-Vpp calibration completed.');
catch analysisError
    converter.runtime.finishRun(runContext, false, analysisError.message);
    rethrow(analysisError);
end
end

function [inputPowerDbm, info] = resolveExplicitSetpoints( ...
        fileNames, manifest, defaultImpedanceOhm)
%RESOLVEEXPLICITSETPOINTS Match a Vpp/dBm setpoint table to source files.

if ~istable(manifest)
    error('converter:adc:InvalidPowerManifest', ...
        'powerSetpoints 必须是 MATLAB table。');
end
variableNames = manifest.Properties.VariableNames;
if ~any(strcmp(variableNames, 'FileName')) || ...
        (~any(strcmp(variableNames, 'InputPowerDbm')) && ...
        ~any(strcmp(variableNames, 'InputVoltageVpp')))
    error('converter:adc:InvalidPowerManifest', ...
        'powerSetpoints 必须包含 FileName，以及 InputPowerDbm 或 InputVoltageVpp。');
end
manifestNames = cellstr(string(manifest.FileName));
[matched, locations] = ismember(fileNames, manifestNames);
if any(~matched)
    error('converter:adc:PowerManifestMismatch', ...
        '显式功率清单未覆盖所有选定 CSV。');
end

fileCount = numel(fileNames);
info = defaultSetpointInfo(fileCount, NaN(fileCount, 1), ...
    defaultImpedanceOhm);
info.setpointManifestUsed = true;
if any(strcmp(variableNames, 'InputPowerDbm'))
    inputPowerDbm = double(manifest.InputPowerDbm(locations));
else
    inputPowerDbm = NaN(fileCount, 1);
end
if any(strcmp(variableNames, 'InputVoltageVpp'))
    info.inputVoltageVpp = double(manifest.InputVoltageVpp(locations));
end
if any(strcmp(variableNames, 'ReferenceImpedanceOhm'))
    info.referenceImpedanceOhm = double( ...
        manifest.ReferenceImpedanceOhm(locations));
end
if any(strcmp(variableNames, 'InputPowerSource'))
    info.inputPowerSource = string(manifest.InputPowerSource(locations));
else
    info.inputPowerSource = repmat( ...
        "explicit input-power manifest", fileCount, 1);
end
if any(strcmp(variableNames, 'InputPowerDefinition'))
    info.inputPowerDefinition = string( ...
        manifest.InputPowerDefinition(locations));
end
if any(~isfinite(info.inputVoltageVpp))
    if any(~isfinite(inputPowerDbm))
        error('converter:adc:InvalidPowerManifest', ...
            '显式清单的 Vpp 或 dBm 必须至少有一项完整提供。');
    end
    info.inputVoltageVpp = converter.adc.dbmToVpp(inputPowerDbm, ...
        info.referenceImpedanceOhm);
end
if any(~isfinite(inputPowerDbm)) && isfinite(defaultImpedanceOhm)
    inputPowerDbm = converter.adc.vppToDbm(info.inputVoltageVpp, ...
        info.referenceImpedanceOhm);
end
end

function info = defaultSetpointInfo(fileCount, inputPowerDbm, impedanceOhm)
%DEFAULTSETPOINTINFO Convert filename dBm labels to Vpp at explicit R.

if nargin < 2 || isempty(inputPowerDbm)
    inputPowerDbm = NaN(fileCount, 1);
end
if nargin < 3 || isempty(impedanceOhm)
    impedanceOhm = 50;
end
info = struct();
info.setpointManifestUsed = false;
if isnan(impedanceOhm) && all(isnan(inputPowerDbm))
    info.inputVoltageVpp = NaN(fileCount, 1);
else
    info.inputVoltageVpp = converter.adc.dbmToVpp(inputPowerDbm, impedanceOhm);
end
info.referenceImpedanceOhm = repmat(impedanceOhm, fileCount, 1);
info.inputPowerSource = repmat( ...
    "dBm value parsed from CSV filename", fileCount, 1);
info.inputPowerDefinition = repmat( ...
    "Vpp=2*sqrt(2*R*1e-3*10^(dBm/10)); filename dBm setpoint", ...
    fileCount, 1);
end

function setpointTable = buildSetpointManifest(fileNames, inputPowerDbm, info)
%BUILDSETPOINTMANIFEST Preserve the exact Vpp setpoint for every file.

setpointTable = table(string(fileNames(:)), inputPowerDbm(:), ...
    info.inputVoltageVpp(:), info.referenceImpedanceOhm(:), ...
    info.inputPowerSource(:), info.inputPowerDefinition(:), ...
    'VariableNames', {'FileName', 'InputPowerDbm', 'InputVoltageVpp', ...
    'ReferenceImpedanceOhm', 'InputPowerSource', 'InputPowerDefinition'});
end

function parameterTable = createParameterTable(config, details)
%CREATEPARAMETERTABLE Record definitions needed to reuse a Vpp scale.

parameterName = {'device_id'; 'analysis_id'; 'channel'; 'sample_rate_hz'; ...
    'test_frequency_hz'; 'adc_bits'; 'adc_full_scale_peak_code'; ...
    'power_range_dbm'; 'power_range_vpp'; 'input_power_setpoint_source'; ...
    'reference_plane'; 'load_definition'; ...
    'setpoint_manifest_used'; 'input_power_reference'; ...
    'reference_impedance_ohm'; 'dbm_to_vpp_formula'; ...
    'codepp_definition'; 'minimum_sine_fit_r2'; ...
    'exclude_frequency_mismatch'; 'calibration_axis'; ...
    'critical_input_threshold_fraction'; 'critical_input_method'};
parameterValue = {char(config.deviceId); char(config.analysisId); ...
    char(details.channelName); num2str(config.sampleRate, 15); ...
    num2str(config.testFrequencyHz, 15); num2str(config.adcBits); ...
    num2str(details.adcFullScalePeakCode, 15); ...
    mat2str(details.powerRangeDbm, 15); ...
    mat2str(details.calibrationPowerRangeVpp, 15); ...
    details.powerSetpointSource; getConfigText(config, 'referencePlane'); ...
    getConfigText(config, 'loadDefinition'); ...
    num2str(details.setpointManifestUsed); ...
    details.inputPowerReference; num2str(details.referenceImpedanceOhm, 15); ...
    details.inputPowerToVppFormula; details.codePpDefinition; ...
    num2str(details.minimumSineFitR2, 15); ...
    num2str(details.excludeFrequencyMismatch); 'CodePp-to-Vpp'; ...
    num2str(details.criticalInput.thresholdFraction, 15); ...
    char(details.criticalInput.method)};
parameterTable = table(parameterName, parameterValue, ...
    'VariableNames', {'Parameter', 'Value'});
end

function calibrationTable = createCalibrationTable(config, details)
%CREATECALIBRATIONTABLE Export the CodePp-to-Vpp calibration formulas.

calibrationItem = {'channel'; 'test_frequency_hz'; ...
    'input_power_setpoint_source'; 'input_power_reference'; ...
    'reference_impedance_ohm'; 'dbm_to_vpp_formula'; ...
    'calibration_point_count'; 'valid_input_power_range_dbm'; ...
    'valid_vpp_range'; 'adc_full_scale_peak_code'; ...
    'codepp_definition'; 'slope_vpp_per_codepp'; 'intercept_vpp'; ...
    'fit_r2'; 'minimum_sine_fit_r2'; 'exclude_frequency_mismatch'; ...
    'formula_codepp_to_vpp'; 'formula_vpp_to_codepp'; ...
    'critical_input_status'; 'critical_input_threshold_fraction'; ...
    'critical_input_threshold_peak_code'; 'critical_input_codepp'; ...
    'critical_input_vpp'; 'critical_input_dbm'; ...
    'critical_input_limiting_rail'; 'last_unclipped_input_vpp'; ...
    'first_clipped_input_vpp'; 'critical_input_extrapolation_ratio'; ...
    'critical_positive_rail_fit_r2'; 'critical_negative_rail_fit_r2'};
calibrationValue = {char(details.channelName); ...
    num2str(config.testFrequencyHz, 15); details.powerSetpointSource; ...
    details.inputPowerReference; num2str(details.referenceImpedanceOhm, 15); ...
    details.inputPowerToVppFormula; num2str(details.calibrationPointCount); ...
    mat2str(details.powerRangeDbm, 15); ...
    mat2str(details.calibrationVppRange, 15); ...
    num2str(details.adcFullScalePeakCode, 15); details.codePpDefinition; ...
    num2str(details.coefficient(1), 15); num2str(details.coefficient(2), 15); ...
    num2str(details.calibrationR2, 15); ...
    num2str(details.minimumSineFitR2, 15); ...
    num2str(details.excludeFrequencyMismatch); ...
    details.forwardFormulaCodePpToVpp; details.inverseFormulaVppToCodePp; ...
    char(details.criticalInput.status); ...
    num2str(details.criticalInput.thresholdFraction, 15); ...
    num2str(details.criticalInput.thresholdPeakCode, 15); ...
    num2str(details.criticalInput.criticalCodePp, 15); ...
    num2str(details.criticalInput.criticalInputVpp, 15); ...
    num2str(details.criticalInput.criticalInputDbm, 15); ...
    char(details.criticalInput.limitingRail); ...
    num2str(details.criticalInput.lastUnclippedInputVpp, 15); ...
    num2str(details.criticalInput.firstClippedInputVpp, 15); ...
    num2str(details.criticalInput.extrapolationRatio, 15); ...
    num2str(details.criticalInput.positiveRailFitR2, 15); ...
    num2str(details.criticalInput.negativeRailFitR2, 15)};
calibrationTable = table(calibrationItem, calibrationValue, ...
    'VariableNames', {'CalibrationItem', 'Value'});
end

function criticalTable = createCriticalInputTable(details)
%CREATECRITICALINPUTTABLE Export one traceable critical-input estimate.

critical = details.criticalInput;
criticalTable = table(string(details.channelName), critical.available, ...
    critical.status, critical.reason, critical.method, ...
    critical.thresholdFraction, critical.thresholdPeakCode, ...
    critical.criticalCodePp, critical.criticalInputVpp, ...
    critical.criticalInputDbm, critical.limitingRail, ...
    critical.positiveRailCriticalVpp, critical.negativeRailCriticalVpp, ...
    critical.positiveRailFitR2, critical.negativeRailFitR2, ...
    critical.lastUnclippedInputVpp, critical.firstClippedInputVpp, ...
    critical.lastUnclippedInputDbm, critical.firstClippedInputDbm, ...
    critical.extrapolationRatio, critical.bracketed, ...
    'VariableNames', {'Channel', 'Available', 'Status', 'Reason', 'Method', ...
    'ThresholdFraction', 'ThresholdPeakCode', 'CriticalCodePp', ...
    'CriticalInputVpp', 'CriticalInputDbm', 'LimitingRail', ...
    'PositiveRailCriticalVpp', 'NegativeRailCriticalVpp', ...
    'PositiveRailFitR2', 'NegativeRailFitR2', ...
    'LastUnclippedInputVpp', 'FirstClippedInputVpp', ...
    'LastUnclippedInputDbm', 'FirstClippedInputDbm', ...
    'ExtrapolationRatio', 'Bracketed'});
end

function printCriticalInput(critical)
%PRINTCRITICALINPUT Print the estimate without promoting it to a verdict.

if ~critical.available
    fprintf('99%% 临界输入估计不可用：%s\n', char(critical.reason));
    return;
end
if isfinite(critical.criticalInputDbm)
    fprintf('99%% 临界输入估计：%.9g Vpp / %+.6g dBm（%s，%s）\n', ...
        critical.criticalInputVpp, critical.criticalInputDbm, ...
        char(critical.limitingRail), char(critical.status));
else
    fprintf('99%% 临界输入估计：%.9g Vpp（%s，%s）\n', ...
        critical.criticalInputVpp, char(critical.limitingRail), ...
        char(critical.status));
end
end

function impedance = getReferenceImpedance(config)
%GETREFERENCEIMPEDANCE Resolve the explicit Vpp reference resistance.

if isfield(config, 'referenceImpedanceOhm') && ...
        ~isempty(config.referenceImpedanceOhm)
    impedance = config.referenceImpedanceOhm;
else
    impedance = 50;
end
if ~isscalar(impedance) || (~isnan(impedance) && ...
        (~isfinite(impedance) || impedance <= 0))
    error('converter:adc:InvalidReferenceImpedance', ...
        'referenceImpedanceOhm 必须为正的有限标量。');
end
end

function value = getConfigText(config, fieldName)
if isfield(config, fieldName) && ~isempty(config.(fieldName))
    value = char(config.(fieldName));
else
    value = 'unknown';
end
end
