classdef ad677ContractTest < matlab.unittest.TestCase
    %AD677CONTRACTTEST Unit contracts required by the AD677 entry.

    properties (TestParameter)
        frequencyCase = struct( ...
            'hz100', struct('text', 'capture_100Hz.csv', 'value', 100), ...
            'khz1', struct('text', 'capture_1kHz.csv', 'value', 1e3), ...
            'khz30', struct('text', 'capture_30kHz.csv', 'value', 30e3))
    end

    methods (TestClassSetup)
        function addRuntime(testCase)
            repositoryRoot = fileparts(fileparts(fileparts( ...
                mfilename('fullpath'))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, '_shared')));
        end
    end

    methods (Test)
        function testFrequencyParsing(testCase, frequencyCase)
            actual = converter.io.parseFrequencyHz(frequencyCase.text);
            testCase.verifyEqual(actual, frequencyCase.value, AbsTol=1e-12);
        end

        function testChannelHeaderMapping(testCase)
            folder = string(tempname);
            mkdir(folder);
            testCase.addTeardown(@() rmdir(folder, 's'));
            filePath = fullfile(folder, 'ad677_ch02_1kHz.csv');
            ad677ContractTest.writeHeaderOnlyCsv(filePath, 2);
            config = ad677ContractTest.channelConfig();
            actual = converter.io.detectChannel(filePath, ...
                'ad677_ch02_1kHz.csv', folder, config);
            testCase.verifyEqual(actual, '677_2');
        end

        function testNoThreeDbCrossingIsCoverageInsufficient(testCase)
            config = ad677ContractTest.bandwidthConfig();
            code = ad677ContractTest.sineCode(2000, 1e3, ...
                config.sampleRate, 4096);
            codeList = {code; code; code};
            [results, details] = converter.adc.calculateBandwidth( ...
                codeList, {'100Hz.csv'; '1kHz.csv'; '30kHz.csv'}, ...
                [100; 1e3; 30e3], config);
            testCase.verifyTrue(isnan(details.bandwidth3dBHz));
            testCase.verifyEqual(details.coverageStatus, "覆盖不足");
            testCase.verifyEqual(unique(results.Conclusion), "暂不能判定");
        end

        function testFrequencyMismatchFlag(testCase)
            config = ad677ContractTest.bandwidthConfig();
            code = ad677ContractTest.sineCode(2000, 2e3, ...
                config.sampleRate, 4096);
            results = converter.adc.calculateBandwidth( ...
                {code; code; code}, {'100Hz.csv'; '1kHz.csv'; '30kHz.csv'}, ...
                [100; 1e3; 30e3], config);
            testCase.verifyTrue(any(results.FrequencyMismatchFlag));
        end

        function testClippingExcludedAndDirectionFields(testCase)
            config = ad677ContractTest.powerConfig();
            codeList = ad677ContractTest.powerCodeList(config.sampleRate);
            setpoints = ad677ContractTest.setpointInfo();
            [results, details] = converter.adc.calculatePowerScale( ...
                codeList, {'0.25Vpp.csv'; '0.5Vpp.csv'; ...
                '0.75Vpp.csv'; '1Vpp.csv'}, NaN(4, 1), ...
                repmat("677_1", 4, 1), config, setpoints);
            testCase.verifyTrue(results.ClippingFlag(end));
            testCase.verifyFalse(results.CalibrationIncluded(end));
            testCase.verifySubstring(results.ExclusionReason(end), ...
                "clipping/near-rail");
            testCase.verifyTrue(ismember('SlopeVppPerCodePp', ...
                results.Properties.VariableNames));
            testCase.verifyTrue(ismember('InterceptVpp', ...
                results.Properties.VariableNames));
            testCase.verifyGreaterThan(details.coefficient(1), 0);
            testCase.verifyEqual(details.criticalInput.thresholdFraction, ...
                0.99, AbsTol=1e-12);
            testCase.verifyEqual(config.clippingThreshold, 0.98, ...
                AbsTol=1e-12);
        end
    end

    methods (Static, Access=private)
        function config = channelConfig()
            config = struct('headerModulePattern', ...
                '(?i)u_ad677_(\d+)/adc_data', ...
                'moduleChannelMap', {{'', '677_1', '677_2'}});
        end

        function config = bandwidthConfig()
            config = struct('sampleRate', 100e3, 'adcBits', 16, ...
                'minimumFitR2', 0.8, 'referencePointCount', 3, ...
                'frequencyMismatchTolerance', 0.02, 'fitCycles', 20, ...
                'minimumFitSamples', 1024, 'clippingMarginCode', 655, ...
                'fitFrequencySource', 'file', ...
                'bandwidthFrequencySource', 'file', ...
                'rejectFrequencyMismatch', false);
        end

        function config = powerConfig()
            config = struct('sampleRate', 100e3, 'adcBits', 16, ...
                'testFrequencyHz', 1e3, 'frequencyMismatchTolerance', 0.02, ...
                'powerRangeVpp', [0.25 1], 'powerSetpointUnit', 'Vpp', ...
                'clippingThreshold', 0.98, 'clippingFractionLimit', 0.001, ...
                'criticalInputThresholdFraction', 0.99, ...
                'plateauChangeThreshold', 0.001, 'fitCycles', 20, ...
                'minimumFitSamples', 1024, 'minimumSineFitR2', 0.8, ...
                'excludeFrequencyMismatchFromPowerScale', false, ...
                'referenceImpedanceOhm', NaN);
        end

        function info = setpointInfo()
            info = struct('setpointManifestUsed', true, ...
                'inputVoltageVpp', [0.25; 0.5; 0.75; 1], ...
                'referenceImpedanceOhm', NaN(4, 1), ...
                'inputPowerSource', repmat("test Vpp", 4, 1), ...
                'inputPowerDefinition', repmat("High-Z Vpp", 4, 1));
        end

        function codeList = powerCodeList(sampleRate)
            codeList = { ...
                ad677ContractTest.sineCode(1000, 1e3, sampleRate, 4096); ...
                ad677ContractTest.sineCode(2000, 1e3, sampleRate, 4096); ...
                ad677ContractTest.sineCode(3000, 1e3, sampleRate, 4096); ...
                max(min(round(40000 * sin(2*pi*1e3*(0:4095)'/sampleRate)), ...
                32767), -32768)};
        end

        function code = sineCode(amplitude, frequencyHz, sampleRate, count)
            time = (0:count-1)' / sampleRate;
            code = round(amplitude * sin(2*pi*frequencyHz*time + 0.2));
        end

        function writeHeaderOnlyCsv(filePath, channel)
            fileId = fopen(filePath, 'w');
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, ['Sample in Buffer,Sample in Window,TRIGGER,' ...
                'u_ad677_to_b9726/u_ad677_%d/adc_data[15:0],' ...
                'u_ad677_to_b9726/u_ad677_%d/adc_data_vld\n'], ...
                channel, channel);
            fprintf(fileId, '0,0,1,0,1\n');
            assert(~isempty(cleanup));
        end
    end
end
