function [fitresult, gof] = sine_fit(data, fin, fs)
%  Create a fit.
%
%  Data for '4 parameters sine fitting' fit:
%      Y Output: data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Oct-2015 16:08:02


%%
aStart = (max(data) - min(data))/2;
aLower = aStart - 100;
aUpper = aStart + 100;
% aUpper = min(aStart+100, 2048);

bStart = fin/fs;
bLower = bStart*0.99;
bUpper = bStart*1.01;
% bLower = bStart * 0.9;
% bUpper = bStart * 1.1;

cStart = 0;
cLower = -pi;
cUpper = pi;

dStart = mean(data);
dLower = dStart - 10;
dUpper = dStart + 10;

data = data(1:round(fs/fin*10)); % only fit 8 periods data
[xData, yData] = prepareCurveData( [], data );

% Set up fittype and options.
ft = fittype( 'a*sin(2*pi*b*x+c)+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';


opts.StartPoint = [aStart, bStart, cStart, dStart];
opts.Lower = [aLower, bLower, cLower, dLower];
opts.Upper = [aUpper, bUpper, cUpper, dUpper];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% %{
figure( 'Name', 'Sine Fitting', 'Visible', 'on');
h = plot( fitresult, xData, yData );
legend( h, 'Data Points', 'Sine Fitting Curve', 'Location', 'NorthEast' );
% Label axes
ylabel('ADC Code')
hold on
end %grid on
% %}
