function [results, details] = calculateIsolation(adcCodeList, channelNames, ...
        drivenChannel, config)
%CALCULATEISOLATION Calculate same-frequency crosstalk isolation.

requiredFields = {'sampleRate', 'adcBits', 'isolationFrequencyHz', ...
    'frequencyMismatchTolerance', 'minimumIsolationDb', 'fitCycles', ...
    'minimumFitSamples'};
converter.runtime.validateConfig(config, requiredFields);
channelNames = string(channelNames(:));
drivenChannel = string(drivenChannel);
fileCount = numel(adcCodeList);
if numel(unique(channelNames)) ~= fileCount
    error('converter:adc:DuplicateChannels', ...
        '存在重复通道文件，请确保每个通道只选择一个 CSV。');
end
drivenMask = channelNames == drivenChannel;
if nnz(drivenMask) ~= 1
    error('converter:adc:DrivenChannelMissing', ...
        '必须且只能找到一个激励通道 %s。', char(drivenChannel));
end
quietMask = ~drivenMask;
if ~any(quietMask)
    error('converter:adc:QuietChannelMissing', '没有安静通道数据，无法计算隔离度。');
end

drivenIndex = find(drivenMask, 1);
drivenFrequencyHz = converter.adc.estimateFrequency( ...
    adcCodeList{drivenIndex}, config.sampleRate);
frequencyMismatchFlag = ...
    abs(drivenFrequencyHz - config.isolationFrequencyHz) / ...
    max(config.isolationFrequencyHz, eps) > config.frequencyMismatchTolerance;
codePp = NaN(fileCount, 1);
fitR2 = NaN(fileCount, 1);
fitResidualRmsCode = NaN(fileCount, 1);
fitConfig = config;
fitConfig.fitMode = 'known';
fitConfig.knownFrequencyHz = drivenFrequencyHz;
for fileIndex = 1:fileCount
    metrics = converter.adc.analyzeDynamicMetrics(adcCodeList{fileIndex}, fitConfig);
    codePp(fileIndex) = metrics.fit.codePp;
    fitR2(fileIndex) = metrics.fit.r2;
    fitResidualRmsCode(fileIndex) = metrics.fit.residualRmsCode;
end

drivenCodePp = codePp(drivenMask);
quietChannels = channelNames(quietMask);
quietCodePp = codePp(quietMask);
isolationDb = 20 * log10(drivenCodePp ./ quietCodePp);
pass = isolationDb >= config.minimumIsolationDb;
quietCount = nnz(quietMask);
results = table( ...
    repmat(drivenChannel, quietCount, 1), quietChannels, ...
    repmat(config.isolationFrequencyHz, quietCount, 1), ...
    repmat(drivenFrequencyHz, quietCount, 1), ...
    repmat(drivenFrequencyHz - config.isolationFrequencyHz, quietCount, 1), ...
    repmat(100 * (drivenFrequencyHz - config.isolationFrequencyHz) / ...
    max(config.isolationFrequencyHz, eps), quietCount, 1), ...
    repmat(frequencyMismatchFlag, quietCount, 1), ...
    repmat(drivenCodePp, quietCount, 1), quietCodePp, isolationDb, ...
    fitR2(quietMask), fitResidualRmsCode(quietMask), pass, ...
    'VariableNames', {'DrivenChannel', 'QuietChannel', 'ExpectedFrequencyHz', ...
    'FrequencyHz', 'FrequencyErrorHz', 'FrequencyErrorPercent', ...
    'FrequencyMismatchFlag', 'DrivenCodePp', 'QuietCodePp', 'IsolationDb', ...
    'QuietFitR2', 'QuietResidualRmsCode', 'Pass'});
details = struct('drivenFrequencyHz', drivenFrequencyHz, ...
    'minimumIsolationDb', config.minimumIsolationDb, ...
    'worstIsolationDb', min(isolationDb));
end

