function fit = fitSine(adcCode, frequencyHz, sampleRate, fitSampleCount)
%FITSINE Fit sine, cosine, and DC terms with linear least squares.

if ~isnumeric(adcCode) || ~isvector(adcCode)
    error('converter:adc:InvalidAdcCode', 'adcCode 必须是数值向量。');
end
if ~isscalar(frequencyHz) || ~isfinite(frequencyHz) || frequencyHz <= 0
    error('converter:adc:InvalidFrequency', '拟合频率必须是正有限标量。');
end
if ~isscalar(sampleRate) || ~isfinite(sampleRate) || sampleRate <= 0
    error('converter:adc:InvalidSampleRate', '采样率必须是正有限标量。');
end

adcCode = double(adcCode(:));
adcCode = adcCode(isfinite(adcCode));
if nargin < 4 || isempty(fitSampleCount)
    fitSampleCount = numel(adcCode);
end
fitSampleCount = min(numel(adcCode), max(1, round(fitSampleCount)));
fitCode = adcCode(1:fitSampleCount);
timeSeconds = (0:fitSampleCount - 1)' / sampleRate;
designMatrix = [sin(2*pi*frequencyHz*timeSeconds), ...
    cos(2*pi*frequencyHz*timeSeconds), ones(fitSampleCount, 1)];
coefficient = designMatrix \ fitCode;
fittedCode = designMatrix * coefficient;
residualCode = fitCode - fittedCode;

amplitudeCode = hypot(coefficient(1), coefficient(2));
phaseRadians = atan2(coefficient(2), coefficient(1));
offsetCode = coefficient(3);
peakCode = offsetCode + amplitudeCode;
valleyCode = offsetCode - amplitudeCode;
totalVariation = fitCode - mean(fitCode);
fitR2 = 1 - sum(residualCode.^2) / max(sum(totalVariation.^2), eps);

fit = struct( ...
    'frequencyHz', frequencyHz, ...
    'sineCoefficient', coefficient(1), ...
    'cosineCoefficient', coefficient(2), ...
    'phaseRadians', phaseRadians, ...
    'amplitudeCode', amplitudeCode, ...
    'codePp', 2 * amplitudeCode, ...
    'offsetCode', offsetCode, ...
    'peakCode', peakCode, ...
    'valleyCode', valleyCode, ...
    'r2', fitR2, ...
    'residualRmsCode', sqrt(mean(residualCode.^2)), ...
    'maximumAbsoluteResidualCode', max(abs(residualCode)), ...
    'fitSampleCount', fitSampleCount, ...
    'samplesPerCycle', sampleRate / frequencyHz, ...
    'timeSeconds', timeSeconds, ...
    'fitCode', fitCode, ...
    'fittedCode', fittedCode);
end

