function requirements = requirement_profile(board, profile)
%REQUIREMENT_PROFILE Return versioned electrical-test requirements.
%   REQUIREMENTS = laser_analysis.requirement_profile(BOARD, PROFILE)
%   returns a table for "digital_lock" or "delay_driver" and "CW" or "GS".
%   CW contains reviewed values transcribed from the two 2026-07 public
%   test specifications. Conflicting source values remain separate rows
%   with state="conflict"; callers must not select one silently.
%
%   Numeric limits use SI-compatible units stated in the unit column.
%   A row with state other than "approved" cannot produce a formal pass or
%   fail judgment.

arguments
    board (1, 1) string
    profile (1, 1) string
end

board = lower(strtrim(board));
profile = upper(strtrim(profile));
if ~ismember(board, ["digital_lock", "delay_driver"])
    error('laser_analysis:UnknownBoard', ...
        'board must be digital_lock or delay_driver.');
end
if ~ismember(profile, ["CW", "GS"])
    error('laser_analysis:UnknownProfile', 'profile must be CW or GS.');
end

source = localSource(board);
if profile == "GS"
    requirements = localGsPlaceholder(board, profile, source);
    return;
end

if board == "digital_lock"
    requirements = localDigitalLockCw(source);
else
    requirements = localDelayDriverCw(source);
end
end

function source = localSource(board)
%LOCALSource Return immutable source identity for a requirement profile.
if board == "digital_lock"
    source.document = "光梳频率梳数字锁定板 测试细则（公开）.docx";
    source.sha256 = ...
        "BCA172A43422FC965EB5131FDF7B221E57D77819EAC1BF19502CAE3D6355BF26";
else
    source.document = "光梳频率梳延迟驱动板 测试细则（公开）.docx";
    source.sha256 = ...
        "9C5FDDBDAAAB3EABA824C64523A61392B5220F16BDD6C21A6FBFC8DC1193B630";
end
end

function out = localDigitalLockCw(source)
%LOCALDIGITALLOCKCW Build the reviewed CW digital-lock requirement rows.
rows = {
    "DL-CW-ADC-FS", "adc", "sample_rate", ">=", 100e6, NaN, "Hz", ...
        "ADC effective sample rate", "5.9.1/Table 5-9", "approved", "";
    "DL-CW-ADC-SFDR", "adc", "sfdr", ">", 65, NaN, "dB", ...
        "RF paths; channel-specific tone frequency", "5.9.2", "approved", "";
    "DL-CW-ADC-INL", "adc", "inl", "<=", 20, NaN, "LSB", ...
        "Near-full-scale sine histogram", "5.9.4", "approved", "";
    "DL-CW-ADC-DNL", "adc", "dnl", "<=", 5, NaN, "LSB", ...
        "Near-full-scale sine histogram", "5.9.4", "approved", "";
    "DL-CW-ADC-RF-SAT", "adc", "rf_saturation", "between", 5, 6, "dBm", ...
        "RF sine input", "5.9.7", "approved", "";
    "DL-CW-ADC-ERR-SAT", "adc", "error_saturation", "between", 2, 2.5, "Vpp", ...
        "Error-signal input", "5.9.7", "approved", "";
    "DL-CW-ADC-NOISE-1HZ", "adc", "asd_1hz", "<=", 10, NaN, ...
        "uV/sqrt(Hz)", "Grounded error-signal input", "5.9.6", "approved", "";
    "DL-CW-ADC-NOISE-HF", "adc", "asd_10_25mhz", "<=", 300, NaN, ...
        "nV/sqrt(Hz)", "Grounded RF input; 10-25 MHz", ...
        "3.2/Table 5-9", "approved", "";
    "DL-CW-ADC-PHASE-BW", "adc", "phase_bandwidth", ">", 2e6, NaN, "Hz", ...
        "-45 degree crossing; synchronous reference required", ...
        "3.2/Table 5-9", "method_gap", ...
        "Detailed procedure records magnitude only.";
    "DL-CW-ADC-TEMP", "adc", "temperature_drift", "<=", 50, NaN, "uV/degC", ...
        "-10 to 45 degC; actual temperature required", ...
        "5.9.8/Table 5-16", "approved", "";
    "DL-CW-ADC-ISOLATION", "adc", "isolation", ">", 40, NaN, "dB", ...
        "Aggressor tone versus victim tone", "5.9.5", "approved", "";
    "DL-CW-DAC-INL", "dac", "inl", "<=", 2, NaN, "mV", ...
        "Static DC code sweep required", "5.10.2", "method_gap", ...
        "Source procedure specifies one full-scale sine, not static INL.";
    "DL-CW-DAC-PN-1HZ", "dac", "phase_noise_1hz", "<", -50, NaN, ...
        "dBc/Hz", "1 MHz carrier", "5.10.3", "approved", "";
    "DL-CW-DAC-PN-100KHZ", "dac", "phase_noise_100khz", "<", -120, NaN, ...
        "dBc/Hz", "1 MHz carrier", "5.10.3", "approved", "";
    "DL-CW-DAC-ASD-1HZ", "dac", "asd_1hz", "<", 75, NaN, ...
        "uV/sqrt(Hz)", "DC output; high-impedance acquisition", ...
        "5.10.4", "approved", "";
    "DL-CW-DAC-RMS", "dac", "integrated_noise", "<", 120, NaN, "uVrms", ...
        "PSD integrated from 1 kHz to 100 kHz", "5.10.4", "approved", "";
    "DL-CW-DAC-ISOLATION", "dac", "isolation", ">", 40, NaN, "dB", ...
        "1 MHz aggressor", "5.10.6", "approved", "";
    "DL-CW-RF100-POWER", "rf", "power", "between", 9, 11, "dBm", ...
        "Three 100 MHz CW reference outputs", "3.2/Table 3-1", ...
        "approved", "";
    "DL-CW-RF100-ADEV-1S", "rf", "adev_1s", "<", 5e-12, NaN, "1", ...
        "Three 100 MHz CW reference outputs", "3.2/Table 3-1", ...
        "approved", "";
    "DL-CW-RF100-ADEV-10000S", "rf", "adev_10000s", "<=", 5e-13, ...
        NaN, "1", "Three 100 MHz CW reference outputs", ...
        "3.2/Table 3-1", "approved", "";
    "DL-CW-RF100-HARMONIC", "rf", "harmonic_suppression", ">=", 30, ...
        NaN, "dBc", "Three 100 MHz CW reference outputs", ...
        "3.2/Table 3-1", "approved", "";
    "DL-CW-RFGTH-POWER", "rf", "power", "between", 4, 9, "dBm", ...
        "CW GTH reference output", "3.2/Table 3-1", "approved", "";
    "DL-CW-RFGTH-ADEV-1S", "rf", "adev_1s", "<", 5e-13, NaN, "1", ...
        "CW GTH at 1 MHz, 100 MHz, 500 MHz, or 1.3 GHz", ...
        "3.2/Table 3-1", "approved", "";
    "DL-CW-RFGTH-ADEV-10000S", "rf", "adev_10000s", "<=", 5e-14, ...
        NaN, "1", "CW GTH at 1.3 GHz", "3.2/Table 3-1", ...
        "approved", "";
    "DL-CW-DELAY-FAST", "loop", "delay", "<", 250e-9, NaN, "s", ...
        "Fast feedback path", "5.12", "approved", "";
    "DL-CW-DELAY-SLOW", "loop", "delay", "<", 5e-6, NaN, "s", ...
        "Slow feedback path", "3.2", "approved", "";
    "DL-CW-DDR-A", "digital", "ddr_capacity", ">=", 1.2e9, NaN, "byte", ...
        "Dynamic cache capacity", "3.2", "conflict", "Conflicts with 320 MB.";
    "DL-CW-DDR-B", "digital", "ddr_capacity", ">=", 320e6, NaN, "byte", ...
        "Dynamic cache capacity", "5.6/Table 5-6", "conflict", ...
        "Conflicts with 1.2 GB."
    };
out = localRowsToTable(rows, "digital_lock", "CW", source);
end

function out = localDelayDriverCw(source)
%LOCALDELAYDRIVERCW Build the reviewed CW delay-driver requirement rows.
rows = {
    "DD-CW-ADC-FS", "adc", "sample_rate", ">=", 20e6, NaN, "Hz", ...
        "AD9245 effective sample rate", "5.4.1", "approved", "";
    "DD-CW-ADC-SFDR", "adc", "sfdr", ">", 65, NaN, "dB", ...
        "Use 1/5/10 MHz test points within Nyquist", "5.4.2", "conflict", ...
        "Narrative also specifies 25 MHz with 20 MSPS.";
    "DD-CW-ADC-INL", "adc", "inl", "<=", 20, NaN, "LSB", ...
        "Near-full-scale sine histogram", "5.4.4", "approved", "";
    "DD-CW-ADC-DNL", "adc", "dnl", "<=", 5, NaN, "LSB", ...
        "Near-full-scale sine histogram", "5.4.4", "approved", "";
    "DD-CW-ADC-RF-SAT", "adc", "rf_saturation", "between", 5, 6, "dBm", ...
        "RF sine input", "5.4.8", "approved", "";
    "DD-CW-ADC-ERR-SAT", "adc", "error_saturation", "between", 2, 2.5, "Vpp", ...
        "Error-signal input", "5.4.8", "approved", "";
    "DD-CW-ADC-BAND", "adc", "input_bandwidth", ">=", 30e3, NaN, "Hz", ...
        "CW path with 30 kHz first-order LPF", "5.4.3", "approved", "";
    "DD-CW-ADC-NOISE", "adc", "asd_1hz", "<=", 10, NaN, ...
        "uV/sqrt(Hz)", "Grounded input", "5.4.6", "approved", "";
    "DD-CW-ADC-TEMP", "adc", "temperature_drift", "<=", 50, NaN, "uV/degC", ...
        "-10 to 45 degC", "5.4.7", "approved", "";
    "DD-CW-ADC-ISOLATION", "adc", "isolation", ">", 40, NaN, "dB", ...
        "1 MHz aggressor", "5.4.5", "approved", "";
    "DD-CW-DAC-PN-1HZ", "dac", "phase_noise_1hz", "<", -50, NaN, ...
        "dBc/Hz", "1 MHz carrier", "5.5.3", "approved", "";
    "DD-CW-DAC-PN-100KHZ", "dac", "phase_noise_100khz", "<", -120, NaN, ...
        "dBc/Hz", "1 MHz carrier", "5.5.3", "approved", "";
    "DD-CW-DAC-ASD-A", "dac", "asd_1hz", "<", 12, NaN, ...
        "uV/sqrt(Hz)", "DC output", "3.2/Table 6", "conflict", ...
        "Detailed section gives 75 uV/sqrt(Hz).";
    "DD-CW-DAC-ASD-B", "dac", "asd_1hz", "<", 75, NaN, ...
        "uV/sqrt(Hz)", "DC output", "5.5.4", "conflict", ...
        "Summary section gives 12 uV/sqrt(Hz).";
    "DD-CW-DAC-RMS-A", "dac", "integrated_noise", "<", 1000, NaN, ...
        "uVrms", "1 kHz to 100 kHz", "3.2/Table 6", "conflict", ...
        "Detailed section gives 120 uVrms.";
    "DD-CW-DAC-RMS-B", "dac", "integrated_noise", "<", 120, NaN, ...
        "uVrms", "1 kHz to 100 kHz", "5.5.4", "conflict", ...
        "Summary section gives 1 mVrms.";
    "DD-CW-DELAY-SLOW", "loop", "delay", "<", 5e-6, NaN, "s", ...
        "AD9245 to DAC slow path", "5.7", "approved", "";
    "DD-CW-ADC128-RMS", "adc128", "rms_noise", "<=", 1, NaN, "mVrms", ...
        "Measurement bandwidth not specified", "5.6", "method_gap", ...
        "Bandwidth must be approved before compliance.";
    "DD-CW-AD677-ASD", "ad677", "asd_1_10khz", "<=", 1, NaN, ...
        "uV/sqrt(Hz)", "Full 1 Hz to 10 kHz band", "3.2", "approved", "";
    "DD-CW-AD677-FS", "ad677", "sample_rate", ">=", 100e3, NaN, "Hz", ...
        "Effective output sample rate", "3.2", "approved", "";
    "DD-CW-AD677-BAND", "ad677", "input_bandwidth", ">=", 12e3, NaN, ...
        "Hz", "Small-signal response", "3.2", "approved", "";
    "DD-CW-AD677-DELAY", "ad677", "delay", "<", 20e-6, NaN, "s", ...
        "Slow ADC feedback path", "3.2", "approved", "";
    "DD-CW-TELEMETRY", "telemetry", "accuracy", "<", 0.5, NaN, "mV", ...
        "Maximum absolute input-referred error", "5.8", "approved", ""
    };
out = localRowsToTable(rows, "delay_driver", "CW", source);
end

function out = localGsPlaceholder(board, profile, source)
%LOCALGSPLACEHOLDER Expose the GS schema without enabling formal judgment.
rows = {
    upper(board) + "-GS-PENDING", "all", "profile_review", "", ...
        NaN, NaN, "", "GS channel and interface map not yet reviewed", ...
        "3.2", "unreviewed", ...
        "Schema only; GS must not be used for formal compliance."
    };
out = localRowsToTable(rows, board, profile, source);
end

function out = localRowsToTable(rows, board, profile, source)
%LOCALROWSTOTABLE Convert row cells to the stable requirement table schema.
out = cell2table(rows, 'VariableNames', { ...
    'requirement_id', 'subsystem', 'metric', 'operator', ...
    'limit_a', 'limit_b', 'unit', 'test_condition', ...
    'source_section', 'state', 'conflict_note'});
out.requirement_id = string(out.requirement_id);
out.subsystem = string(out.subsystem);
out.metric = string(out.metric);
out.operator = string(out.operator);
out.unit = string(out.unit);
out.test_condition = string(out.test_condition);
out.source_section = string(out.source_section);
out.state = string(out.state);
out.conflict_note = string(out.conflict_note);
out.board = repmat(string(board), height(out), 1);
out.profile = repmat(string(profile), height(out), 1);
out.source_document = repmat(source.document, height(out), 1);
out.source_sha256 = repmat(source.sha256, height(out), 1);
out = movevars(out, {'board', 'profile'}, 'Before', 'requirement_id');
end
