function result = run_ad9245_g100_psd_asd(cfg)
%RUN_AD9245_G100_PSD_ASD Shared AD9245-FPGA-DAC G100 PSD/ASD runner.
%   RESULT contains the resolved configuration, source/calibration evidence,
%   spectra, summary tables, and every generated output path.  The result is
%   conditional on the configured FPGA gain and retains DAC/Pico background.
%   Override cfg.outputDir for smoke tests; no formal report is modified.

arguments
    cfg (1, 1) struct
end
cfg = validateConfig(cfg);
adc = string(cfg.channel);
dac = string(cfg.dacChannel);
prefix = string(cfg.caseName);

required = {cfg.inputMat, cfg.adcCalibrationCsv, cfg.dacCalibrationCsv};
for k = 1:numel(required)
    if ~exist(required{k}, 'file')
        error('laser_analysis:MissingSource', ...
            'Required source does not exist: %s', required{k});
    end
end
if ~exist(cfg.outputDir, 'dir'), mkdir(cfg.outputDir); end
if isfield(cfg, 'requirementSource') && exist(cfg.requirementSource, 'file')
    copyfile(cfg.requirementSource, ...
        fullfile(cfg.outputDir, 'ADC_noise_requirement_source.png'));
end

adcTable = readtable(cfg.adcCalibrationCsv);
adcMask = strcmp(string(adcTable.fitName), 'primary_non_near_rail');
if nnz(adcMask) ~= 1
    error('laser_analysis:CalibrationRow', ...
        'Expected exactly one primary %s calibration row.', adc);
end
kAdc = adcTable.slopeVPerCode(adcMask);
adcReferencePlane = string(adcTable.referencePlane(adcMask));
dacTable = readtable(cfg.dacCalibrationCsv);
if height(dacTable) ~= 1 || ~ismember('slope_vpp_per_code', dacTable.Properties.VariableNames)
    error('laser_analysis:CalibrationRow', ...
        'Expected one DAC summary row with slope_vpp_per_code.');
end
kDac = dacTable.slope_vpp_per_code(1);
if ~isfinite(kAdc) || ~isfinite(kDac) || kAdc <= 0 || kDac <= 0
    error('laser_analysis:CalibrationValue', 'Invalid ADC or DAC calibration slope.');
end
inputPerOutputScale = kAdc / (abs(cfg.fpgaGain) * kDac);

raw = load(cfg.inputMat);
if ~isfield(raw, 'A') || ~isfield(raw, 'Tinterval')
    error('laser_analysis:MatSchema', 'MAT must contain A and Tinterval.');
end
rawVector = double(raw.A(:));
rawVectorCount = numel(rawVector);
metadataLength = rawVectorCount;
if cfg.useMatLength && isfield(raw, 'Length') && ...
        ~isempty(raw.Length) && isfinite(double(raw.Length(1)))
    metadataLength = min(rawVectorCount, max(1, floor(double(raw.Length(1)))));
end
trailingSamplesExcluded = rawVectorCount - metadataLength;
outputVoltage = rawVector(1:metadataLength);
finiteMask = isfinite(outputVoltage);
nonfiniteSamplesExcluded = nnz(~finiteMask);
outputVoltage = outputVoltage(finiteMask);
dt = double(raw.Tinterval(1));
if ~isfinite(dt) || dt <= 0
    error('laser_analysis:MatSchema', 'Invalid Tinterval in source MAT.');
end
fs = 1 / dt;
n = numel(outputVoltage);
duration = n / fs;
nyquist = fs / 2;
if n < round(cfg.welchWindowSeconds * fs)
    error('laser_analysis:ShortRecord', ...
        'Record is shorter than the configured Welch window.');
end

outputMean = mean(outputVoltage);
outputZeroMean = outputVoltage - outputMean;
inputEquivalent = outputZeroMean * inputPerOutputScale;
rawMedian = median(outputVoltage);
rawMad = median(abs(outputVoltage - rawMedian));
robustSigma = 1.4826 * rawMad;
if robustSigma > 0
    outlier8SigmaCount = nnz(abs(outputVoltage - rawMedian) > 8 * robustSigma);
else
    outlier8SigmaCount = 0;
end
outlier8SigmaPercent = 100 * outlier8SigmaCount / n;

windowSamples = min(round(cfg.welchWindowSeconds * fs), n);
overlapSamples = floor(windowSamples * cfg.overlapRatio);
nfft = windowSamples;
window = hann(windowSamples, 'periodic');
[psdOutput, frequency] = pwelch(outputZeroMean, window, ...
    overlapSamples, nfft, fs, 'onesided');
asdOutput = sqrt(max(psdOutput, 0));
psdInput = psdOutput * inputPerOutputScale^2;
asdInput = sqrt(max(psdInput, 0));
df = frequency(2) - frequency(1);
step = windowSamples - overlapSamples;
segmentCount = 1 + floor((n - windowSamples) / step);

fullWindow = hann(n, 'periodic');
[psdFullOutput, frequencyFull] = periodogram( ...
    outputZeroMean, fullWindow, n, fs, 'onesided');
asdFullOutput = sqrt(max(psdFullOutput, 0));
psdFullInput = psdFullOutput * inputPerOutputScale^2;
asdFullInput = sqrt(max(psdFullInput, 0));
fullRecordDf = frequencyFull(2) - frequencyFull(1);

[~, index1Hz] = min(abs(frequency - 1));
frequencyAt1Hz = frequency(index1Hz);
outputAsd1HzUv = asdOutput(index1Hz) * 1e6;
outputPsd1Hz = psdOutput(index1Hz);
inputAsd1HzNv = asdInput(index1Hz) * 1e9;
inputPsd1Hz = psdInput(index1Hz);

bandName = ["0.1-1Hz"; "0.8-1.2Hz"; "1-10Hz"; "10-100Hz"; ...
    "100Hz-1kHz"; "1-10kHz"; "10-30kHz"; "30-50kHz"; ...
    "0.1Hz-30kHz"; "0.1Hz-50kHz"];
bandStart = [0.1; 0.8; 1; 10; 100; 1e3; 10e3; 30e3; 0.1; 0.1];
bandEnd = [1; 1.2; 10; 100; 1e3; 10e3; 30e3; 50e3; 30e3; 50e3];
bandSummaryTable = makeBandSummary(frequency, psdOutput, psdInput, ...
    bandName, bandStart, bandEnd, df, adc, dac);
oneHzMask = bandMask(frequency, 0.8, 1.2, df);
oneHzOutputUv = asdOutput(oneHzMask) * 1e6;
oneHzInputNv = asdInput(oneHzMask) * 1e9;

windowSensitivityTable = makeWindowSensitivity(outputZeroMean, fs, ...
    cfg.windowSensitivitySeconds, cfg.overlapRatio, inputPerOutputScale, adc, dac);
[segmentStabilityTable, segmentInputNv] = makeSegmentStability( ...
    outputZeroMean, fs, window, windowSamples, step, nfft, ...
    inputPerOutputScale, adc, dac);
topSpurTable = makeTopSpurs(frequencyFull, psdFullOutput, ...
    inputPerOutputScale, cfg.spurCount, cfg.spurMinimumFrequencyHz, ...
    nyquist, cfg.spurMinimumSeparationHz, adc, dac);

[sourceManifestTable, inputSha256Manifest] = buildSourceManifest(cfg);
if nyquist >= cfg.extendedAnalysisEndHz
    extendedBandCoverage = "满足";
else
    extendedBandCoverage = "不满足";
end
if inputAsd1HzNv <= cfg.asdLimitAt1HzUvPerSqrtHz * 1e3
    formalConclusion = "满足";
    comparisonOperator = "<=";
else
    formalConclusion = "不满足";
    comparisonOperator = ">";
end
conclusionReason = sprintf([ ...
    'Conditional on configured G=%g, %s input-equivalent ASD at %.9g Hz ' ...
    'is %.9g uV/sqrtHz %s %.9g uV/sqrtHz; DAC/Pico background retained.'], ...
    cfg.fpgaGain, adc, frequencyAt1Hz, inputAsd1HzNv / 1e3, ...
    comparisonOperator, cfg.asdLimitAt1HzUvPerSqrtHz);

oneHzSummaryTable = table(prefix, string(cfg.inputMat), n, fs, duration, ...
    nyquist, rawVectorCount, metadataLength, trailingSamplesExcluded, ...
    nonfiniteSamplesExcluded, outputMean, std(outputZeroMean), ...
    min(outputVoltage), max(outputVoltage), outlier8SigmaCount, ...
    outlier8SigmaPercent, kAdc, kDac, cfg.fpgaGain, inputPerOutputScale, ...
    adcReferencePlane, string(cfg.fpgaGainEvidence), ...
    cfg.welchWindowSeconds, windowSamples, overlapSamples, ...
    cfg.overlapRatio, nfft, df, segmentCount, fullRecordDf, ...
    frequencyAt1Hz, outputAsd1HzUv, outputPsd1Hz, ...
    inputAsd1HzNv, inputPsd1Hz, median(oneHzOutputUv), ...
    mean(oneHzOutputUv), max(oneHzOutputUv), median(oneHzInputNv), ...
    mean(oneHzInputNv), max(oneHzInputNv), min(segmentInputNv), ...
    median(segmentInputNv), max(segmentInputNv), 0, ...
    cfg.requirementBandEndHz, cfg.extendedAnalysisEndHz, ...
    cfg.asdLimitAt1HzUvPerSqrtHz, extendedBandCoverage, ...
    string(cfg.requirementTestCondition), formalConclusion, ...
    string(conclusionReason), ...
    "mean removed; periodic Hann; no DAC/Pico baseline subtraction", ...
    inputSha256Manifest);
oneHzSummaryTable.Properties.VariableNames = summaryVariableNames(adc, dac);

fullSpectrumTable = table(frequency, psdOutput, asdOutput, ...
    asdOutput * 1e6, psdInput, asdInput, asdInput * 1e9);
fullSpectrumTable.Properties.VariableNames = { ...
    'Frequency_Hz', sprintf('%s_Output_PSD_V2_per_Hz', dac), ...
    sprintf('%s_Output_ASD_V_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_uV_per_sqrtHz', dac), ...
    sprintf('%s_InputEq_PSD_V2_per_Hz', adc), ...
    sprintf('%s_InputEq_ASD_V_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_nV_per_sqrtHz', adc)};
lowMask = frequencyFull <= cfg.lowFrequencyExportEndHz;
lowFrequencyTable = table(frequencyFull(lowMask), psdFullOutput(lowMask), ...
    asdFullOutput(lowMask) * 1e6, psdFullInput(lowMask), ...
    asdFullInput(lowMask) * 1e9);
lowFrequencyTable.Properties.VariableNames = { ...
    'Frequency_Hz', sprintf('%s_Output_PSD_V2_per_Hz', dac), ...
    sprintf('%s_Output_ASD_uV_per_sqrtHz', dac), ...
    sprintf('%s_InputEq_PSD_V2_per_Hz', adc), ...
    sprintf('%s_InputEq_ASD_nV_per_sqrtHz', adc)};
analysisParametersTable = buildParameterTable(cfg, adcReferencePlane, ...
    kAdc, kDac, nfft, formalConclusion);

outputFiles = outputPaths(cfg, prefix, adc, dac);
writetable(oneHzSummaryTable, outputFiles.oneHzSummary, 'Encoding', 'UTF-8');
writetable(bandSummaryTable, outputFiles.bandSummary, 'Encoding', 'UTF-8');
writetable(fullSpectrumTable, outputFiles.fullSpectrum, 'Encoding', 'UTF-8');
writetable(lowFrequencyTable, outputFiles.lowFrequency, 'Encoding', 'UTF-8');
writetable(topSpurTable, outputFiles.topSpurs, 'Encoding', 'UTF-8');
writetable(windowSensitivityTable, outputFiles.windowSensitivity, 'Encoding', 'UTF-8');
writetable(segmentStabilityTable, outputFiles.segmentStability, 'Encoding', 'UTF-8');
writetable(analysisParametersTable, outputFiles.parameters, 'Encoding', 'UTF-8');
writetable(sourceManifestTable, outputFiles.sourceManifest, 'Encoding', 'UTF-8');

makeSpectrumFigure(frequency, asdOutput * 1e6, frequencyAt1Hz, ...
    outputAsd1HzUv, sprintf('%s output ASD', dac), ...
    sprintf('%s output ASD (uV/sqrt(Hz))', dac), ...
    outputFiles.outputAsdPlot, cfg, [0.05 0.35 0.75], NaN, '');
makeSpectrumFigure(frequency, psdOutput, frequencyAt1Hz, outputPsd1Hz, ...
    sprintf('%s output PSD', dac), sprintf('%s output PSD (V^2/Hz)', dac), ...
    outputFiles.outputPsdPlot, cfg, [0.10 0.55 0.35], NaN, '');
makeSpectrumFigure(frequency, asdInput * 1e9, frequencyAt1Hz, ...
    inputAsd1HzNv, sprintf('%s input-equivalent ASD', adc), ...
    sprintf('%s input-equivalent ASD (nV/sqrt(Hz))', adc), ...
    outputFiles.inputAsdPlot, cfg, [0.55 0.20 0.65], ...
    cfg.asdLimitAt1HzUvPerSqrtHz * 1e3, 'ASD limit');
makeSpectrumFigure(frequency, psdInput, frequencyAt1Hz, inputPsd1Hz, ...
    sprintf('%s input-equivalent PSD', adc), ...
    sprintf('%s input-equivalent PSD (V^2/Hz)', adc), ...
    outputFiles.inputPsdPlot, cfg, [0.80 0.30 0.10], ...
    (cfg.asdLimitAt1HzUvPerSqrtHz * 1e-6)^2, 'PSD limit');
makeStabilityFigure(windowSensitivityTable, segmentStabilityTable, ...
    outputFiles.stabilityPlot, cfg.plotDpi, adc, dac);
writeTextSummary(outputFiles.textSummary, cfg, oneHzSummaryTable, ...
    bandSummaryTable, adc, dac);

result = struct;
result.config = cfg;
result.sourceFiles = sourceManifestTable;
result.calibrationSource = struct('adcCsv', string(cfg.adcCalibrationCsv), ...
    'dacCsv', string(cfg.dacCalibrationCsv), 'adcSlopeVPerCode', kAdc, ...
    'dacSlopeVPerCode', kDac, 'adcReferencePlane', adcReferencePlane, ...
    'fpgaGain', cfg.fpgaGain, 'inputPerOutputScale', inputPerOutputScale);
result.spectrum = struct('frequencyHz', frequency, ...
    'outputPsdV2PerHz', psdOutput, 'outputAsdVPerSqrtHz', asdOutput, ...
    'inputEquivalentPsdV2PerHz', psdInput, ...
    'inputEquivalentAsdVPerSqrtHz', asdInput, ...
    'fullRecordFrequencyHz', frequencyFull, ...
    'fullRecordOutputPsdV2PerHz', psdFullOutput, ...
    'fullRecordInputEquivalentPsdV2PerHz', psdFullInput);
result.summaryTable = oneHzSummaryTable;
result.bandSummaryTable = bandSummaryTable;
result.windowSensitivityTable = windowSensitivityTable;
result.segmentStabilityTable = segmentStabilityTable;
result.topSpurTable = topSpurTable;
result.outputFiles = outputFiles;
save(outputFiles.mat, 'result', '-v7.3');
end

function cfg = validateConfig(cfg)
required = {'channel', 'dacChannel', 'variant', 'caseName', 'inputMat', ...
    'adcCalibrationCsv', 'dacCalibrationCsv', 'outputDir', ...
    'fpgaGain', 'fpgaGainEvidence', 'requirementBandEndHz', ...
    'extendedAnalysisEndHz', 'asdLimitAt1HzUvPerSqrtHz', ...
    'requirementTestCondition', 'welchWindowSeconds', 'overlapRatio', ...
    'windowSensitivitySeconds', 'lowFrequencyExportEndHz', ...
    'spurMinimumFrequencyHz', 'spurMinimumSeparationHz', 'spurCount', ...
    'plotDpi', 'useMatLength', 'scriptVersion'};
for k = 1:numel(required)
    if ~isfield(cfg, required{k})
        error('laser_analysis:MissingConfig', 'Missing cfg.%s.', required{k});
    end
end
end

function mask = bandMask(frequency, startHz, endHz, df)
tolerance = max(abs(df) * 1e-6, eps(max(abs(frequency))) * 10);
mask = frequency >= startHz - tolerance & frequency <= endHz + tolerance;
end

function out = makeBandSummary(f, pOut, pIn, names, starts, ends, df, adc, dac)
nBand = numel(names);
values = NaN(nBand, 13);
binCount = zeros(nBand, 1);
for k = 1:nBand
    mask = bandMask(f, starts(k), ends(k), df);
    fx = f(mask); po = pOut(mask); pi = pIn(mask);
    if isempty(fx), continue; end
    ao = sqrt(max(po, 0)) * 1e6; ai = sqrt(max(pi, 0)) * 1e9;
    binCount(k) = numel(fx);
    [outMax, outIndex] = max(ao); [inMax, inIndex] = max(ai);
    values(k, :) = [median(ao), mean(ao), percentile(ao, 95), outMax, ...
        fx(outIndex), integrateNoise(fx, po), median(ai), mean(ai), ...
        percentile(ai, 95), inMax, fx(inIndex), integrateNoise(fx, pi), df];
end
out = table(names, starts, ends, binCount, values(:, 1), values(:, 2), ...
    values(:, 3), values(:, 4), values(:, 5), values(:, 6), ...
    values(:, 7), values(:, 8), values(:, 9), values(:, 10), ...
    values(:, 11), values(:, 12), values(:, 13));
out.Properties.VariableNames = {'Band', 'Start_Hz', 'End_Hz', 'BinCount', ...
    sprintf('%s_Output_ASD_Median_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_Mean_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_P95_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_Max_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_Max_Frequency_Hz', dac), ...
    sprintf('%s_Output_IntegratedNoise_uVrms', dac), ...
    sprintf('%s_InputEq_ASD_Median_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_Mean_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_P95_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_Max_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_Max_Frequency_Hz', adc), ...
    sprintf('%s_InputEq_IntegratedNoise_uVrms', adc), ...
    'FrequencyResolution_Hz'};
end

function value = integrateNoise(f, p)
if numel(f) > 1, value = sqrt(trapz(f, p)) * 1e6; else, value = NaN; end
end

function value = percentile(data, pct)
sorted = sort(double(data(:)));
if isempty(sorted), value = NaN; return; end
position = 1 + (numel(sorted) - 1) * pct / 100;
lo = floor(position); hi = ceil(position);
if lo == hi, value = sorted(lo);
else, value = sorted(lo) * (hi - position) + sorted(hi) * (position - lo); end
end

function out = makeWindowSensitivity(x, fs, seconds, overlapRatio, scale, adc, dac)
nCase = numel(seconds);
df = NaN(nCase, 1); segments = NaN(nCase, 1); at1 = NaN(nCase, 1);
outAsd = NaN(nCase, 1); inAsd = NaN(nCase, 1);
inMedian = NaN(nCase, 1); inMax = NaN(nCase, 1);
for k = 1:nCase
    nw = min(round(seconds(k) * fs), numel(x));
    if nw < numel(x), no = floor(nw * overlapRatio); else, no = 0; end
    [p, f] = pwelch(x, hann(nw, 'periodic'), no, nw, fs, 'onesided');
    ao = sqrt(max(p, 0)); ai = ao * scale;
    [~, idx] = min(abs(f - 1)); df(k) = f(2) - f(1);
    mask = bandMask(f, 0.8, 1.2, df(k));
    segments(k) = 1 + floor((numel(x) - nw) / (nw - no));
    at1(k) = f(idx); outAsd(k) = ao(idx) * 1e6; inAsd(k) = ai(idx) * 1e9;
    inMedian(k) = median(ai(mask)) * 1e9; inMax(k) = max(ai(mask)) * 1e9;
end
out = table(seconds, df, segments, at1, outAsd, inAsd, inMedian, inMax);
out.Properties.VariableNames = {'Window_s', 'Df_Hz', 'SegmentCount', ...
    'FrequencyAt1Hz_Hz', sprintf('%s_Output_ASD_1Hz_uV_per_sqrtHz', dac), ...
    sprintf('%s_InputEq_ASD_1Hz_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_0p8_1p2Hz_Median_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_0p8_1p2Hz_Max_nV_per_sqrtHz', adc)};
end

function [out, inputNv] = makeSegmentStability(x, fs, window, nw, step, nfft, scale, adc, dac)
startSample = (1:step:(numel(x) - nw + 1)).';
startTime = (startSample - 1) / fs;
outputUv = NaN(numel(startSample), 1); inputNv = NaN(numel(startSample), 1);
for k = 1:numel(startSample)
    idx = startSample(k):(startSample(k) + nw - 1);
    segment = x(idx) - mean(x(idx));
    [p, f] = periodogram(segment, window, nfft, fs, 'onesided');
    [~, at1] = min(abs(f - 1));
    outputUv(k) = sqrt(p(at1)) * 1e6;
    inputNv(k) = sqrt(p(at1)) * scale * 1e9;
end
out = table(startSample, startTime, outputUv, inputNv);
out.Properties.VariableNames = {'StartSample', 'StartTime_s', ...
    sprintf('%s_Output_ASD_1Hz_uV_per_sqrtHz', dac), ...
    sprintf('%s_InputEq_ASD_1Hz_nV_per_sqrtHz', adc)};
end

function out = makeTopSpurs(f, p, scale, count, minF, maxF, separation, adc, dac)
candidate = find(f >= minF & f <= maxF & isfinite(p) & p > 0);
[~, order] = sort(p(candidate), 'descend'); candidate = candidate(order);
selected = zeros(count, 1); selectedCount = 0;
for k = 1:numel(candidate)
    idx = candidate(k);
    if selectedCount == 0 || all(abs(f(idx) - f(selected(1:selectedCount))) >= separation)
        selectedCount = selectedCount + 1; selected(selectedCount) = idx;
        if selectedCount == count, break; end
    end
end
selected = selected(1:selectedCount); rank = (1:selectedCount).';
frequencyHz = f(selected); outputPsd = p(selected); outputAsdUv = sqrt(outputPsd) * 1e6;
inputPsd = outputPsd * scale^2; inputAsdNv = sqrt(inputPsd) * 1e9;
out = table(rank, frequencyHz, outputPsd, outputAsdUv, inputPsd, inputAsdNv);
out.Properties.VariableNames = {'rank', 'frequency_Hz', ...
    sprintf('%s_Output_PSD_V2_per_Hz', dac), ...
    sprintf('%s_Output_ASD_uV_per_sqrtHz', dac), ...
    sprintf('%s_InputEq_PSD_V2_per_Hz', adc), ...
    sprintf('%s_InputEq_ASD_nV_per_sqrtHz', adc)};
end

function [out, manifest] = buildSourceManifest(cfg)
roles = ["noise MAT"; "ADC measured calibration summary"; ...
    "DAC measured calibration summary"];
paths = string({cfg.inputMat; cfg.adcCalibrationCsv; cfg.dacCalibrationCsv});
if isfield(cfg, 'auxiliaryEvidence') && exist(cfg.auxiliaryEvidence, 'file')
    roles(end + 1, 1) = string(cfg.auxiliaryEvidenceRole);
    paths(end + 1, 1) = string(cfg.auxiliaryEvidence);
end
if isfield(cfg, 'requirementSource') && exist(cfg.requirementSource, 'file')
    roles(end + 1, 1) = "requirement screenshot";
    paths(end + 1, 1) = string(cfg.requirementSource);
end
sizeBytes = zeros(numel(paths), 1); modified = strings(numel(paths), 1);
hashes = strings(numel(paths), 1);
for k = 1:numel(paths)
    info = dir(char(paths(k))); sizeBytes(k) = info.bytes;
    modified(k) = string(datetime(info.datenum, 'ConvertFrom', ...
        'datenum', 'Format', 'yyyy-MM-dd HH:mm:ss'));
    hashes(k) = sha256(char(paths(k)));
end
out = table(roles, paths, sizeBytes, modified, hashes, ...
    'VariableNames', {'sourceRole', 'sourcePath', 'sourceSizeBytes', ...
    'sourceModifiedTime', 'sourceSha256'});
manifest = strjoin(roles + "=" + hashes, ';');
end

function names = summaryVariableNames(adc, dac)
names = {'CaseName', 'InputFile', 'SampleCount', 'Fs_Hz', 'Duration_s', ...
    'Nyquist_Hz', 'RawVectorCount', 'MAT_Metadata_Length', ...
    'TrailingSamplesExcluded', 'NonfiniteSamplesExcluded', ...
    sprintf('%s_OutputMean_V', dac), sprintf('%s_OutputStd_V', dac), ...
    sprintf('%s_OutputMin_V', dac), sprintf('%s_OutputMax_V', dac), ...
    'Outlier8SigmaCount', 'Outlier8SigmaPercent', ...
    sprintf('k_%s_V_per_code', adc), sprintf('k_%s_V_per_code', dac), ...
    'FPGA_Gain', sprintf('Scale_%sin_per_%sout', adc, dac), ...
    sprintf('%s_CalibrationReferencePlane', adc), 'FPGA_GainEvidence', ...
    'WelchWindow_s', 'WelchWindowSamples', 'WelchOverlapSamples', ...
    'WelchOverlapRatio', 'NFFT', 'FrequencyResolution_Hz', ...
    'WelchSegmentCount', 'FullRecordResolution_Hz', 'FrequencyAt1Hz_Hz', ...
    sprintf('%s_Output_ASD_1Hz_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_PSD_1Hz_V2_per_Hz', dac), ...
    sprintf('%s_InputEq_ASD_1Hz_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_PSD_1Hz_V2_per_Hz', adc), ...
    sprintf('%s_Output_ASD_0p8_1p2Hz_Median_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_0p8_1p2Hz_Mean_uV_per_sqrtHz', dac), ...
    sprintf('%s_Output_ASD_0p8_1p2Hz_Max_uV_per_sqrtHz', dac), ...
    sprintf('%s_InputEq_ASD_0p8_1p2Hz_Median_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_0p8_1p2Hz_Mean_nV_per_sqrtHz', adc), ...
    sprintf('%s_InputEq_ASD_0p8_1p2Hz_Max_nV_per_sqrtHz', adc), ...
    sprintf('Segment_%s_InputEq_ASD_1Hz_Min_nV_per_sqrtHz', adc), ...
    sprintf('Segment_%s_InputEq_ASD_1Hz_Median_nV_per_sqrtHz', adc), ...
    sprintf('Segment_%s_InputEq_ASD_1Hz_Max_nV_per_sqrtHz', adc), ...
    'RequirementBandStart_Hz', 'RequirementBandEnd_Hz', ...
    'ExtendedAnalysisEnd_Hz', 'ASD_Limit_1Hz_uV_per_sqrtHz', ...
    'ExtendedBandCoverage', 'RequirementTestCondition', ...
    'FormalConclusion', 'ConclusionReason', 'ProcessingNote', ...
    'Input_SHA256_Manifest'};
end

function out = buildParameterTable(cfg, referencePlane, kAdc, kDac, nfft, conclusion)
parameter = ["analysis_name"; "script_version"; "input_mat"; ...
    "output_directory"; "variant"; "requirement_test_condition"; ...
    "input_variable"; "sample_rate_source"; "sample_count_policy"; ...
    "mean_removal"; "welch_window"; "welch_overlap"; "welch_nfft"; ...
    "adc_scale"; "adc_scale_source"; "adc_reference_plane"; ...
    "dac_scale"; "dac_scale_source"; "fpga_gain"; "fpga_gain_evidence"; ...
    "input_equivalent_formula"; "baseline_subtraction"; "formal_conclusion"];
value = [string(cfg.caseName); string(cfg.scriptVersion); string(cfg.inputMat); ...
    string(cfg.outputDir); string(cfg.variant); string(cfg.requirementTestCondition); ...
    "A"; "1/Tinterval in MAT"; ...
    sprintf('useMatLength=%d', cfg.useMatLength); "global arithmetic mean removed"; ...
    sprintf('%g s periodic Hann', cfg.welchWindowSeconds); ...
    sprintf('%g percent', cfg.overlapRatio * 100); string(nfft); ...
    string(kAdc); string(cfg.adcCalibrationCsv); string(referencePlane); ...
    string(kDac); string(cfg.dacCalibrationCsv); string(cfg.fpgaGain); ...
    string(cfg.fpgaGainEvidence); ...
    "S_input_eq = S_output * [k_ADC/(abs(G)*k_DAC)]^2"; ...
    "none; total DAC/PicoScope background retained"; string(conclusion)];
unit = [""; "text"; "path"; "path"; "text"; "text"; "text"; "text"; ...
    "text"; "text"; "text"; "ratio"; "samples"; "V/code"; "path"; ...
    "text"; "V/code"; "path"; "ratio"; "text"; "formula"; "text"; "state"];
evidenceClass = ["configured"; "configured"; "directly observed"; "configured"; ...
    "configured"; "user-supplied requirement"; "directly observed"; ...
    "directly observed"; "configured"; "calculated"; "configured"; ...
    "configured"; "configured"; "measured calibration"; ...
    "measured calibration source"; "limited reference-plane evidence"; ...
    "measured calibration"; "measured calibration source"; ...
    "configured condition"; "not independently verified"; "calculated"; ...
    "configured"; "conditional conclusion"];
out = table(parameter, value, unit, evidenceClass);
end

function paths = outputPaths(cfg, prefix, adc, dac)
base = char(prefix);
paths = struct;
paths.oneHzSummary = fullfile(cfg.outputDir, [base '_one_hz_summary.csv']);
paths.bandSummary = fullfile(cfg.outputDir, [base '_band_summary.csv']);
paths.fullSpectrum = fullfile(cfg.outputDir, [base '_full_PSD_ASD.csv']);
paths.lowFrequency = fullfile(cfg.outputDir, [base '_low_frequency_full_record_PSD_ASD.csv']);
paths.topSpurs = fullfile(cfg.outputDir, [base '_top_spurs.csv']);
paths.windowSensitivity = fullfile(cfg.outputDir, [base '_window_sensitivity.csv']);
paths.segmentStability = fullfile(cfg.outputDir, [base '_segment_stability.csv']);
paths.parameters = fullfile(cfg.outputDir, 'analysis_parameters.csv');
paths.sourceManifest = fullfile(cfg.outputDir, 'source_manifest.csv');
paths.mat = fullfile(cfg.outputDir, [base '_PSD_ASD_result.mat']);
paths.outputAsdPlot = fullfile(cfg.outputDir, ...
    sprintf('%s_%s_output_ASD.png', base, dac));
paths.outputPsdPlot = fullfile(cfg.outputDir, ...
    sprintf('%s_%s_output_PSD.png', base, dac));
paths.inputAsdPlot = fullfile(cfg.outputDir, ...
    sprintf('%s_%s_input_equiv_ASD.png', base, adc));
paths.inputPsdPlot = fullfile(cfg.outputDir, ...
    sprintf('%s_%s_input_equiv_PSD.png', base, adc));
paths.stabilityPlot = fullfile(cfg.outputDir, [base '_1Hz_stability.png']);
paths.textSummary = fullfile(cfg.outputDir, 'result_summary.txt');
end

function makeSpectrumFigure(f, value, pointF, pointValue, titleText, yText, path, cfg, color, limit, limitLabel)
fig = figure('Visible', 'off', 'Color', 'w', 'Position', [100 100 1250 720]);
mask = f >= 0.1 & f <= cfg.extendedAnalysisEndHz & isfinite(value) & value > 0;
loglog(f(mask), value(mask), 'Color', color, 'LineWidth', 0.9); hold on;
plot(pointF, pointValue, 'o', 'MarkerFaceColor', [0.85 0.15 0.15]);
xline(1, '--'); xline(cfg.requirementBandEndHz, '--');
if isfinite(limit) && limit > 0, yline(limit, '--r', limitLabel); end
grid on; box on; xlabel('Frequency (Hz)'); ylabel(yText); title(titleText);
xlim([0.1 cfg.extendedAnalysisEndHz]);
exportgraphics(fig, path, 'Resolution', cfg.plotDpi, 'BackgroundColor', 'white');
close(fig);
end

function makeStabilityFigure(sensitivity, segments, path, dpi, adc, dac)
adcColumn = sprintf('%s_InputEq_ASD_1Hz_nV_per_sqrtHz', adc);
fig = figure('Visible', 'off', 'Color', 'w', 'Position', [100 100 1200 680]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile; plot(sensitivity.Window_s, sensitivity.(adcColumn), '-o');
grid on; xlabel('Welch window (s)'); ylabel('Input-eq ASD (nV/sqrt(Hz))');
title('Window sensitivity');
nexttile; plot((1:height(segments)).', segments.(adcColumn), '-o');
grid on; xlabel('Segment index'); ylabel('Input-eq ASD (nV/sqrt(Hz))');
title('Segment variation');
sgtitle(sprintf('AD9245 %s/%s G100 conditional stability', adc, dac));
exportgraphics(fig, path, 'Resolution', dpi, 'BackgroundColor', 'white');
close(fig);
end

function writeTextSummary(path, cfg, oneHz, bands, adc, dac)
fid = fopen(path, 'w');
if fid < 0, warning('Unable to write %s.', path); return; end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
adcAsd = sprintf('%s_InputEq_ASD_1Hz_nV_per_sqrtHz', adc);
dacAsd = sprintf('%s_Output_ASD_1Hz_uV_per_sqrtHz', dac);
adcMedian = sprintf('%s_InputEq_ASD_Median_nV_per_sqrtHz', adc);
fprintf(fid, '%s PSD/ASD result\n', cfg.caseName);
fprintf(fid, 'N=%d, fs=%.12g Hz, duration=%.12g s\n', ...
    oneHz.SampleCount, oneHz.Fs_Hz, oneHz.Duration_s);
fprintf(fid, '%s output ASD at 1 Hz: %.9g uV/sqrtHz\n', dac, oneHz.(dacAsd));
fprintf(fid, '%s input-equivalent ASD at 1 Hz: %.9g nV/sqrtHz\n', ...
    adc, oneHz.(adcAsd));
fprintf(fid, 'Formal conclusion: %s\n', char(oneHz.FormalConclusion));
fprintf(fid, 'Evidence: %s\n', char(cfg.auxiliaryEvidenceRole));
for k = 1:height(bands)
    fprintf(fid, '%s median: %.9g nV/sqrtHz\n', ...
        char(bands.Band(k)), bands.(adcMedian)(k));
end
end

function hash = sha256(path)
[status, output] = system(sprintf('certutil -hashfile "%s" SHA256', ...
    strrep(char(path), '"', '""')));
if status ~= 0, hash = ""; return; end
token = regexp(output, '[0-9A-Fa-f]{64}', 'match', 'once');
if isempty(token), hash = ""; else, hash = lower(string(token)); end
end
